### ISSUE TITLE
problem with NanoPreprocess

### ISSUE THREAD

**Issue by MSajek** [biocorecrg/master_of_pores#101]
I try to run nanopreprocess.nf and have the following error:

N E X T F L O W  ~  version 19.04.0
Launching `nanopreprocess.nf` [cheesy_boyd] - revision: dd396dfd00
╔╦╗┌─┐┌─┐┌┬┐┌─┐┬─┐  ┌─┐┌─┐  ╔═╗╔═╗╦═╗╔═╗╔═╗
║║║├─┤└─┐ │ ├┤ ├┬┘  │ │├┤   ╠═╝║ ║╠╦╝║╣ ╚═╗
╩ ╩┴ ┴└─┘ ┴ └─┘┴└─  └─┘└    ╩  ╚═╝╩╚═╚═╝╚═╝
                                                                                       
====================================================
BIOCORE@CRG Preprocessing of Nanopore direct RNA - N F  ~  version 0.1
====================================================

kit                       : SQK-RNA002
flowcell                  : FLO-MIN106
fast5                     : /home/programs/master_of_pores/NanoPreprocess/test/*.fast5
reference                 : /media/dysk3/marcin/L2nanopore/gencode.v38.transcripts.fa
annotation                : 

ref_type                  : transcriptome
seq_type                  : RNA

output                    : /media/dysk3/marcin/L2nanopore/0hr/testOut
qualityqc                 : 5
granularity               : 

basecaller                : guppy
basecaller_opt            : --cpu_threads_per_caller 45
GPU                       : OFF
demultiplexing            : guppy 
demultiplexing_opt        : -m pAmps-final-actrun_newdata_nanopore_UResNet20v2_model.030.h5 
demulti_fast5		      : OFF

filter                    : 
filter_opt                : 
mapper                    : minimap2
mapper_opt                : -ax map-ont -t 45
map_type                  : spliced

counter                   : NO
counter_opt               : 

downsampling			  : 

variant_caller            : NO
variant_opt               : 

email                     :
Skipping the email
executor >  local (2)
[a2/40f906] process > testInput      [  0%] 0 of 1
[fe/14252e] process > logBaseCalling [100%] 1 of 1 ✔
*********************************
: Guppy Basecalling Software, (C) Oxford Nanopore Technologies, Limited. Version 3.4.5+fb1fbfb
executor >  local (2)
[a2/40f906] process > testInput      [100%] 1 of 1 ✔
[fe/14252e] process > logBaseCalling [100%] 1 of 1 ✔
*********************************
: Guppy Basecalling Software, (C) Oxford Nanopore Technologies, Limited. Version 3.4.5+fb1fbfb
FLO-MIN106 SQK-RNA002           rna_r9.4.1_70bps_hac
*********************************

ERROR ~ For input string: "multi-read"

 -- Check script 'nanopreprocess.nf' at line: 177 or see '.nextflow.log' file for more details

I run basic command:

nextflow run nanopreprocess.nf -with-docker

I know that fast5 files are ok, because everything works fine when I use guppy/minimap2/other software alone.

Thank you for help

**Comment by lucacozzuto** [comment]
Hi, can you try the little dataset we include in the repo, please?

**Comment by lucacozzuto** [comment]
Hi, is this issue solved?
