### ISSUE TITLE
Nanomod after Nanoporprocess_simple runs with no modules except "index_reference"

### ISSUE THREAD

**Issue by AnunayS** [biocorecrg/master_of_pores#102]
I ran nanopreprocess_simple with 4 RNA fastq.gz files.

the output folders are named as nanopreprocess-0B,nanopreprocess-0T,nanopreprocess-3B,nanopreprocess-3T and saved in path <Desktop/Anunay/>.

**Now when I am running nanomod, the script runs completely withinh 30 seconds with following output:**

*****************   Input files    *******************
input_path                              : /home/sequencing/Desktop/Anunay/nanopreprocess*
comparison                              : /home/sequencing/master_of_pores/NanoMod/comparison.tsv

********** reference has to be the genome *************
reference                               : /home/sequencing/Desktop/Anunay/gencode.v38.transcripts.fasta
output                                  : /home/sequencing/Desktop/Anunay/MOP_results/Nanomod/

coverage                                : 5
************* tombo and epinano params ****************
tombo_opt                               : tombo detect_modifications alternative_model --alternate-bases 5mC 6mA

epinano_opt                             : 

email                                   : 

executor >  local (1)
[-        ] process > resquiggling                 -
[-        ] process > getModifications             -
[39/c0e9f0] process > index_reference              [100%] 1 of 1 ✔
[-        ] process > CallVariantsForEpinano       -
[-        ] process > calcVarFrequenciesForEpinano -
[-        ] process > makeEpinanoPlotsMis          -
[-        ] process > makeEpinanoPlotsIns          -
[-        ] process > makeEpinanoPlotsDel          -
Skipping the email

Pipeline BIOCORE@CRG Master of Pore completed!
Started at  2021-09-02T13:00:54.030514+05:30
Finished at 2021-09-02T13:01:07.547766+05:30
Time elapsed: 13.5s
Execution status: OK

As we can see it is not running any other processes for methylation calling.

**My params file is as below:**

params {
    input_path      	= "/home/sequencing/Desktop/Anunay/nanopreprocess*"
    comparison         = "/home/sequencing/master_of_pores/NanoMod/comparison.tsv"

    reference          = "/home/sequencing/Desktop/Anunay/gencode.v38.transcripts.fasta"

    output             = "/home/sequencing/Desktop/Anunay/MOP_results/Nanomod/"
    coverage           = 5

    tombo_opt          = "tombo detect_modifications alternative_model --alternate-bases 5mC 6mA"

    epinano_opt        = ""
    
    email              = ""
}

**And the comparison file is as below:** 

nanopreprocess-3T	nanopreprocess-3B
nanopreprocess-3T	nanopreprocess-0T
nanopreprocess-3T	nanopreprocess-0B
nanopreprocess-3B	nanopreprocess-0B

I think it is unable to read comparison file, but what changes can I make to have it running properly.

Please let me know what mistake I am doing or what step I am missing.

Thankyou.

**Comment by lucacozzuto** [comment]
Hi, NanoMod needs the output from NanoPreprocess. In case you use NanoPreprocessSimple you need to have the same output as generated by NanoPreprocess, including basecalled fast5.

**Comment by AnunayS** [comment]
I am giving the ouput folder location for the nanopreprocesssimple, but still it is not running the pipeline completely.

does the output folder names for each sample (generated by nanopreprocess) should match with the entries in the comparison file?

Or do I have to put the folder complete path in the comparison file?

I have written in the above comment, please see if the comparsion file is correct or not.

**Comment by lucacozzuto** [comment]
Hi,
the problem is that you miss the basecalled fast5 files. NanoMod works with the output of NanoPreprocess. The comparison file is fine if they are tab separated. Please look at the documentation of NanoMod

Luca
