### ISSUE TITLE
Issue with NanoMod

### ISSUE THREAD

**Issue by Maheen94** [biocorecrg/master_of_pores#103]
I am struggling with the initial part of NanoMod pipeline.
[0d/d5307d] NOTE: Process 'index_reference' terminated with an error exit status (126) -- Error is ignored

Command:
nextflow run nanomod.nf -input_path "/home/carter-balaj/EpiTX/input/" \ -comparison "/home/carter-balaj/EpiTX/master_of_pores/NanoMod/comparison.tsv" -reference "/home/carter-balaj/EpiTX/master_of_pores/anno/reference.fasta.gz" \ -tombo_opt "--num-bases 5" -epinano_opt "" -with-docker

**Comment by lucacozzuto** [comment]
Hi, can you send me the log of your execution? And the command line?

**Comment by ADelgadoT** [comment]
Hi, 

Could you decompress the reference file and then re-run the pipeline? Let me know if it worked or not. 

Thanks

**Comment by lucacozzuto** [comment]
Hi, is this issue solved?
