### ISSUE TITLE
Error starting Nanopreprocess - >logbasecalling

### ISSUE THREAD

**Issue by agamblindr** [biocorecrg/master_of_pores#104]
Fairly new to this. I'm running a virtual machine Ubuntu on my windows laptop.
The error I'm having is:
Error executing process > 'logBaseCalling'
Is it that the program can't run guppy?

How do I fix this?

I see this error when I run:
(base) aust@aust-VirtualBox:~/master_of_pores/NanoPreprocess$ nextflow run nanopreprocess.nf -with-docker
N E X T F L O W  ~  version 21.04.0
Launching `nanopreprocess.nf` [high_lovelace] - revision: 070dd5f042

╔╦╗┌─┐┌─┐┌┬┐┌─┐┬─┐  ┌─┐┌─┐  ╔═╗╔═╗╦═╗╔═╗╔═╗
║║║├─┤└─┐ │ ├┤ ├┬┘  │ │├┤   ╠═╝║ ║╠╦╝║╣ ╚═╗
╩ ╩┴ ┴└─┘ ┴ └─┘┴└─  └─┘└    ╩  ╚═╝╩╚═╚═╝╚═╝
                                                                                       
====================================================
BIOCORE@CRG Preprocessing of Nanopore direct RNA - N F  ~  version 0.1
====================================================

kit                       : SQK-RNA001
flowcell                  : FLO-MIN106
fast5                     : /home/aust/master_of_pores/NanoPreprocess/../data/multifast/*.fast5
reference                 : /home/aust/master_of_pores/NanoPreprocess/../anno/curlcake_constructs.fasta.gz
annotation                : 

ref_type                  : transcriptome
seq_type                  : cDNA

output                    : /home/aust/master_of_pores/NanoPreprocess/multifast
qualityqc                 : 5
granularity               : 

basecaller                : guppy
basecaller_opt            : 
GPU                       : OFF
demultiplexing            :  
demultiplexing_opt        : -m pAmps-final-actrun_newdata_nanopore_UResNet20v2_model.030.h5 
demulti_fast5		      : OFF

filter                    : 
filter_opt                : 
mapper                    : graphmap2
mapper_opt                : 
map_type                  : spliced

counter                   : YES
counter_opt               : 

downsampling			  : 

variant_caller            : NO
variant_opt               : 

email                     : 

executor >  local (3)
[e3/4f0be5] process > testInput (multifast5_1.fa... [100%] 1 of 1 ✔
[61/c1ba86] process > logBaseCalling                [  0%] 0 of 1
[80/572c95] process > baseCalling (guppy-multifa... [  0%] 0 of 1
[-        ] process > concatenateFastQFiles         -
[-        ] process > QC                            -
[-        ] process > fastQC                        -
[-        ] process > mapping                       -
[-        ] process > counting                      -
[-        ] process > joinCountQCs                  -
[-        ] process > alnQC                         -
[-        ] process > joinAlnQCs                    -
[-        ] process > alnQC2                        -
[-        ] process > multiQC                       -
Skipping the email

MultiFast5 files detected!
Error executing process > 'logBaseCalling'

Caused by:
  Process `logBaseCalling` terminated with an error exit status (127)

Command executed:

  echo '*********************************'
executor >  local (3)
[e3/4f0be5] process > testInput (multifast5_1.fa... [100%] 1 of 1 ✔
[61/c1ba86] process > logBaseCalling                [100%] 1 of 1, failed: 1 ✘
[-        ] process > baseCalling (guppy-multifa... -
[-        ] process > concatenateFastQFiles         -
[-        ] process > QC                            -
[-        ] process > fastQC                        -
[-        ] process > mapping                       -
[-        ] process > counting                      -
[-        ] process > joinCountQCs                  -
[-        ] process > alnQC                         -
[-        ] process > joinAlnQCs                    -
[-        ] process > alnQC2                        -
[-        ] process > multiQC                       -
Skipping the email

MultiFast5 files detected!
Error executing process > 'logBaseCalling'

Caused by:
  Process `logBaseCalling` terminated with an error exit status (127)

Command executed:

  echo '*********************************'
  guppy_basecaller --version
  guppy_basecaller --print_workflows | grep FLO-MIN106 | grep SQK-RNA001
  echo '*********************************'

Command exit status:
  127

Command output:
  *********************************

Command error:
  .command.sh: line 3: guppy_basecaller: command not found

Work dir:
  /home/aust/master_of_pores/NanoPreprocess/work/61/c1ba86e34fedfaeb88f639c41aad5a

Tip: you can replicate the issue by changing to the process work dir and entering the command `bash .command.run`

**Comment by lucacozzuto** [comment]
Yes, did you place correctly the guppy executables and the rest of the files? do sh INSTALL.sh in the root of master of pores to download the version 3.4.5

**Comment by agamblindr** [comment]
That worked! Thank you! 

New question - How much RAM do I need to run this? I have a 1T SSD and 16 GB on an intel i7. The error I'm running into now states that I need at least 20 GB of memory in order to continue. Is there a workaround to run it on 16GB RAM or do I need to upgrade?

**Comment by lucacozzuto** [comment]
Hi,
you can change the requirements changing the nextflow.global.config file. You can reduce there the resources needed

Luca

**Comment by agamblindr** [comment]
Thank you!
