### ISSUE TITLE
Guppy_basecaller issue

### ISSUE THREAD

**Issue by amol007-123** [biocorecrg/master_of_pores#106]
Hello,
        I'm trying to perform PoreCov pipeline but i having a error regrading Guppy_basecaller. the error is following

Command error:
  [guppy/error] *common::LoadModuleFromFatbin: Loading fatbin file shared.fatbin failed with: CUDA error at /builds/ofan/ont_core_cpp/ont_core/common/cuda_common.cpp:54: CUDA_ERROR_NO_BINARY_FOR_GPU
  
  .command.sh: line 2:    30 Segmentation fault      (core dumped) guppy_basecaller -c dna_r9.4.1_450bps_hac.cfg -i fast5 -s fastq_tmp -x auto -r

please help me to solve the issue.
![Screenshot from 2021-11-18 10-20-46](https://user-images.githubusercontent.com/70798370/142355569-84e48f81-0e53-4252-bf3c-709b3d53f934.png)
 and i have updated cuda installed.

**Comment by lucacozzuto** [comment]
Hi, I think this is not the right repo :)
