### ISSUE TITLE
Copying ami-0bf3a9a6cb7a5ea9f to US-East Virginia?

### ISSUE THREAD

**Issue by xguse** [biocorecrg/master_of_pores#107]
So I need to operate in us-east-1. From there I cant "see" `ami-0bf3a9a6cb7a5ea9f` in the searches. I CAN see it if I change to eu-central-1.

when I try to copy the AMI to my region it says that i dont have permissions to access the AMI's storage. I am not sure if that is a permission set on my group's side of things or specific to the AMI's settings. 

If I can't copy it to my region, how do you suggest I go about getting an EC2 in us-east-1 set up with your AMI?

**Comment by toniher** [comment]
Hi @xguse, underlying EBS snapshot was not shared (https://docs.aws.amazon.com/AWSEC2/latest/UserGuide/ebs-modifying-snapshot-permissions.html). Could you test now and let us know?

**Comment by xguse** [comment]
You are amazing! Its in the process of transfer now!

Thank you guys so much for this tool and for being so responsive.

**Comment by lucacozzuto** [comment]
You are welcome! 
We have also a beta version that will allow the use of AWS batch with the possibility to have multiple GPU etc.
Not yet finished but can be useful
https://github.com/biocorecrg/MOP2
