### ISSUE TITLE
Newer guppy versions dont seem to have fast5_type.py

### ISSUE THREAD

**Issue by xguse** [biocorecrg/master_of_pores#110]
There are a LOT of newer versions of guppy than what both the MOP and MOP2 pipelines suggest using. This causes problems like `fast5_type.py` not being found when newer versions of guppy are used.

Is there a way around this? what do you suggest? can I just not use MOP?

**Comment by lucacozzuto** [comment]
Sorry, I don't get the question. fast5_type.py is a piece of code we added to MOP for detecting multi and single fast5 files. So is not a problem of guppy. When you install other versions of guppy you should not remove it from where it is.

**Comment by xguse** [comment]
Yeah sorry, I did finally realize that. I'm closing this
