### ISSUE TITLE
The "nanopreprocess.nf" exits with an error, as the guppy_basecaller 6.0.1 outputs fastq files in subdirectories "pass" and "fail".

### ISSUE THREAD

**Issue by sbridgett** [biocorecrg/master_of_pores#111]
Thank you for developing the Master of Pores software. I'm running it on a recent direct RNA dataset. 

I downloaded the guppy_basecaller software from the Oxford Nanopore website. However, it is a newer version 6.0.1:  "ont-guppy-cpu_6.0.1_linux64.tar.gz", rather than the earlier "ont-guppy_3.1.5_linux64.tar.gz" version given in your installation instructions.

This newer version outputs the fastq files in subdirectories "18_out/pass/" and "18_out/fail/", which then causes the following ".command.sh" in "NanoPreprocess" work directory to fail, as it expects the the fastq files to be in the main "18_out" directory, so the "cat 18_out/*.fastq" doesn't copy the fastq sequences, and the "rm 18_out/*.fastq" exits with an error code as the "18_out/" directory itself doesn't contain the fastq files (instead they are in subdirectories "18_out/pass/" and "18_out/fail/") 

```
#!/bin/bash -ue
guppy_basecaller  --flowcell FLO-MIN106 --kit SQK-RNA002 --fast5_out  -i ./ --save_path ./18_out --cpu_threads_per_caller 1 --gpu_runners_per_device 1 --num_callers  8
cat 18_out/*.fastq  | awk '{if (NR%4==2) gsub("U","T"); print}'  >> 18.fastq
rm 18_out/*.fastq
gzip 18.fastq
```

So in the "NanoPreprocess/nanopreprocess.nf" script I changed the following two lines
From:
`      cat ${idfile}_out/*.fastq ${RNA_conv_cmd} >> ${idfile}.fastq`
to:
`      cat ${idfile}_out/pass/*.fastq ${RNA_conv_cmd} >> ${idfile}.fastq`

And from: 
`      rm ${idfile}_out/*.fastq`
to:
`      rm 18_out/pass/*.fastq  18_out/fail/*.fastq`

I am wondering if this change will change the final results, and if this change could be made to the current "nanopreprocess.nf" script on github?

Below are more details of that "NanoPreprocess/work/8e/0620........0e3d28/18_out" subdirectory contents:

> fail (a directory)
> pass (a directory)
> sequencing_summary.txt
> sequencing_telemetry.js
> workspace (a directory)
> guppy_basecaller_log-2022-01-15_10-11-22.log
> 

Where:
18_out/fail contains:

> fastq_runid_23ede8c05.........e964e9_0_0.fastq

18_out/pass contains:

> fastq_runid_23ede8c05bfb5.........e964e9_0_0.fastq

18_out/workspace contains:

>    FAQ17.........fast5.temp

Thank you.

**Comment by lucacozzuto** [comment]
Dear @sbridgett, this basecaller is not supported with this version of master of pores. I suggest you to use the newer Master of Pores 2 we just released:

https://github.com/biocorecrg/MOP2

In mop_preprocess you can indicate custom parameters to the basecalling step. You can make a new custom *_opt.tsv file with this row

```
#step	tool	extrapars
basecalling	guppy	"--disable_qscore_filtering"
``` 

I don't recommend you to go on with only "pass" reads since most of modified ones could have lower quality.

**Comment by sbridgett** [comment]
Thank you for your helpful reply above about the guppy_basecaller version and using the newer Master of pores version 2, and the option to disable the qscore filtering so includes reads that wouldn't pass that qc filter. 

I've installed that Master of Pores 2 and it ran the basecalling. However it subsequently stops with an error about being unable to install the multiqc docker image. I'll explain this on the MOP2 github.
