### ISSUE TITLE
Add GPU basecalling support

### ISSUE THREAD

**Issue by lpryszcz** [biocorecrg/master_of_pores#12]
hi Luca, 

I've added the binaries for GPU-enabled basecalling as  `programs/ont-guppy_3.1.5_linux64.tar.gz`. Note, those binaries support both, CPU and GPU basecalling, thus you can remove CPU-only binaries (`ont-guppy_3.1.5_linux64.tar.gz`). 

In order to enable basecalling on GPU, you'll need to [install cuda-toolkit](https://developer.nvidia.com/cuda-downloads?target_os=Linux&target_arch=x86_64&target_distro=Ubuntu&target_version=1804&target_type=debnetwork). 

Let me know if you need any help!

**Comment by lucacozzuto** [comment]
Hi @lpryszcz I see that guppy ha these two opions:
  --gpu_runners_per_device arg      Number of runners per GPU device.
  --cpu_threads_per_caller arg      Number of CPU worker threads per 
                                    basecaller.

Maybe gpu_runners_per_device instead of cpu_threads_per_caller has to be used when we have GPU support?

**Comment by lucacozzuto** [comment]
please can we check the pipeline in GPU mode? @lpryszcz

**Comment by lucacozzuto** [comment]
It was really a pain, but I managed... Added here https://github.com/biocorecrg/master_of_pores/commit/83bc42883cc94ad1fd2fa7870300960eaa81975a

**Comment by lucacozzuto** [comment]
Please let me know if the GPU supports work :)

**Comment by enovoa** [comment]
@obegik

**Comment by lpryszcz** [comment]
solved https://medium.com/@lpryszcz/containers-with-cuda-support-5467f393649f
