### ISSUE TITLE
homogenise the output when demultiplexed

### ISSUE THREAD

**Issue by lucacozzuto** [biocorecrg/master_of_pores#14]
Ideally we should have a similar output so that can be used by other modules.

**Comment by lucacozzuto** [comment]
The main problem is to demultiplex also the fast5 files...

**Comment by enovoa** [comment]
i think huanle might have a script that does this?

**Comment by lucacozzuto** [comment]
The pipeline now demultiplex the fast5 files too. I also added a shel script for converting the output into a format compatible with the other two modules when using demultiplexing.
https://github.com/biocorecrg/master_of_pores/commit/a70b68dfb3336c9b6f9e52b2dd614e3246a378f0
