### ISSUE TITLE
add gene counting feature for direct RNA sequencing

### ISSUE THREAD

**Issue by enovoa** [biocorecrg/master_of_pores#14]
https://github.com/a-slide/NanoCount

NanoCount estimates transcript abundance from ONT direct-RNA Sequencing reads mapped to a transcriptome. It uses an expectation-maximization approach like RSEM, Kallisto, salmon, etc to handle multi-mapping reads. The reads must be mapped to the transcript set using minimap2.

**Comment by Huanle** [comment]
I sent you the gff file that you need for this test through email.

**Comment by lucacozzuto** [comment]
thanks!

**Comment by lucacozzuto** [comment]
PS: I would need fast5 files for testing.

**Comment by Huanle** [comment]
Hi Luca,
You might have missed the email i sent. The path to the fast5 files is '/no_backup_isis/enovoa/data/ont/rt_cDNA/cDNAB120905_both_good' .
Let me know if you can access it.
Thanks.

**Comment by lucacozzuto** [comment]
Duplicate of https://github.com/biocorecrg/master_of_pores/issues/17
