### ISSUE TITLE
combining results from tailfindr and nanopolish

### ISSUE THREAD

**Issue by lucacozzuto** [biocorecrg/master_of_pores#15]
Please can help me on which is the best way to combine the results?

**Comment by enovoa** [comment]
@JMiguelRamirez can you please advice Luca and/or provide script to do so? (i.e. the tailfindr vs nanopolish script that was used to compare the results? Thanks!

**Comment by JMiguelRamirez** [comment]
Hi Luca, what do we exactly need? Is it just combining the results from
tailfindr and nanopolish or also comparing them and some downstream
analyses?

I am attaching my code in R for comparing both approaches, executing it outputs a directory with many plots. It compares the outputs of each
software, but it also compares three replicates of S. cerevisiae WT and
three of ime4∆ looking for differentially expressed genes. The input is the
tailfindr and nanopolish outputs already containing information about the
gene names, I think Huanle already sent code for including the gene names
in the outputs, but if not, I can provide it.

I will be more active on gitter in case you need something else,
 polya_analysis.zip
<https://drive.google.com/a/alumni.esci.upf.edu/file/d/1a_BmhkFIKajznped_Mh_nMYLWyBvAei_/view?usp=drive_web>

**Comment by lucacozzuto** [comment]
Hi!
For now I would need just something for comparing the results of each
program. Instead for comparing tombo and nanopolish I would need comparison
of sample Vs KO between replicates.

Luca

Il mer 25 dic 2019, 19:54 José Miguel Ramírez <notifications@github.com> ha
scritto:

**Comment by lucacozzuto** [comment]
done
