### ISSUE TITLE
finish docs running.md

### ISSUE THREAD

**Issue by enovoa** [biocorecrg/master_of_pores#16]
These two sections need to be finished to include how to use them. 

## NanoTail
Data produced by NanoPreprocess are needed for this module. 

Finish writing usage

## NanoMod
Data produced by NanoPreprocess are needed for this module. 

Finish writing usage

**Comment by lucacozzuto** [comment]
I split the documentation in three files:
https://github.com/biocorecrg/master_of_pores/blob/master/docs/nanopreprocess.md
https://github.com/biocorecrg/master_of_pores/blob/master/docs/nanomod.md
https://github.com/biocorecrg/master_of_pores/blob/master/docs/nanotail.md
