### ISSUE TITLE
Second module

### ISSUE THREAD

**Issue by lucacozzuto** [biocorecrg/master_of_pores#17]
Dear all, let's try to think about the second module... The first one should go from demultiplexing to read counts... what about the second one?

**Comment by Huanle** [comment]
@lucacozzuto 
from bam, we would love to get:

- expression level quantification, similar to but not equal to the number of reads mapped to a specific genomic feature (if it is RNAseq data). I recommend [NanoCount](https://github.com/a-slide/NanoCount)  for this purpose. 
- features/metrics used for predicting base modification, for this i will share with you a shell script that include all downstream analyses. but i also think that this could be an independent feature of the pipeline.
- we can get alignemnt metrics as well making comparisons between samples using program such as [nanocomp](https://github.com/wdecoster/nanocomp)
- in some cases (e.g., polya identification) bam files are also essential. 
- ...
As you can see, there are a few processes that need BAM files as inputs. This means we need to to conceive an efficient way of both generation and uses of them. 
Maybe we can meet and discuss this further. When most, if not all bioinfomaticians are around in the next few days.

**Comment by enovoa** [comment]
- PolyA selection: tailfindr and nanopolish
https://github.com/adnaniazi/tailfindr
https://github.com/jts/nanopolish
- Gene counting: NanoCount & HTSeq
https://github.com/a-slide/NanoCount
https://htseq.readthedocs.io/en/release_0.11.1/
- RNA modification prediction: Tombo & EpiNano
https://github.com/enovoa/EpiNano
https://github.com/nanoporetech/tombo

**Comment by lucacozzuto** [comment]
I just miss tailfindr. I'll add to the docker

**Comment by lucacozzuto** [comment]
I made three new issues, each one for a pipeline and close this.
