### ISSUE TITLE
how can we see which models are available within the demultiplexing algorithm?

### ISSUE THREAD

**Issue by enovoa** [biocorecrg/master_of_pores#17]
I have tried to dig across the folders of master of pores and cannot find where they are. can you pls help? thanks!

**Comment by lucacozzuto** [comment]
Likely you are not looking at review branch. Inside NanoProcessing you have
a folder with models

Il mar 7 gen 2020, 19:17 Eva Novoa <notifications@github.com> ha scritto:

**Comment by novoalabmember** [comment]
Thanks, i was looking into the wrong branch. which model is the default?

**Comment by lucacozzuto** [comment]
The one written in the params.config

L

Il mer 8 gen 2020, 02:18 novoalab <notifications@github.com> ha scritto:

**Comment by Huanle** [comment]
@enovoa @novoalab, model 030 is the default one, which is also the most reliable one so far.
