### ISSUE TITLE
adding custom parameters to programs

### ISSUE THREAD

**Issue by lucacozzuto** [biocorecrg/master_of_pores#19]
We can have more pipeline parameters for allowing custom parameters to the programs... what do you think?

**Comment by Huanle** [comment]
@lucacozzuto yes, for sure, especially for basecalling and reads mapping.

**Comment by lucacozzuto** [comment]
So we have to rethink about using custom parameters for mapping to transcriptome or genome? We can get rid of this difference and give the full power to the user...

**Comment by lucacozzuto** [comment]
I added this possibility in https://github.com/biocorecrg/master_of_pores/commit/d3db843d9b492807e39ed07f3dd21100441bcd1b
