### ISSUE TITLE
NanoPreprocessing counting genes/transcripts option

### ISSUE THREAD

**Issue by ADelgadoT** [biocorecrg/master_of_pores#19]
It is possible that the user wants to map against the genome and doesn't care at all about the gene counts. Currently, if the ref_type == genome, an annotation file (GTF) is required by the pipeline as it is needed for counting genes and not always the annotation file is available. 

Could it be possible to leave the user decide if he/she wants the counts? In this way, users that only want to map to the genome and do not have an annotation file can also use the pipeline. 

It is also true that at the moment, you can avoid this issue by playing with the available settings but I believe that the mentioned option would be more user friendly. What do you think about it? 

Thanks :D

**Comment by lucacozzuto** [comment]
This was implemented but not visible in the params.config. It is the option **counter** that can be YES or NO or OFF or EMPTY (to skip the counts). I added that option in https://github.com/biocorecrg/master_of_pores/commit/9eea86ae1867b2eb470ae8e8bc6361e127a083da
