### ISSUE TITLE
incorporate nanocompore in nanomod

### ISSUE THREAD

**Issue by enovoa** [biocorecrg/master_of_pores#20]
Documentation: https://nanocompore.rna.rocks
Github repo: https://github.com/tleonardi/nanocompore 

The first two steps needed prior to running nanocompore, which are:
1) Realign the raw signal-level data to the kmers of the reference with Nanopolish
2) Collapse Nanopolish output by kmer using NanopolishComp

Are already written in the form of nextflow workflow
https://github.com/tleonardi/nanocompore_pipeline 

Alternatively, they can be run by doing the steps described here: 
https://github.com/tleonardi/nanocompore/blob/master/docs/data_preparation.md

Last part (ie. step 3, running nanocompore sampcomp) needs to be incorporated in the form of nextflow workflow, but here are the details on how to run it:
https://nanocompore.rna.rocks/demo/SampComp_usage/

**Comment by Huanle** [comment]
@lucacozzuto let me know if you ran into any problem related to this program

**Comment by lucacozzuto** [comment]
Hi, in nanomod we already requiggled the data using tombo. I'm wondering if we need to redo everything with nanopolish like they say. Or we can use the tombo resquiggling.
Let me know.

**Comment by enovoa** [comment]
Needs to be nanopolish - works much better.

**Comment by lucacozzuto** [comment]
Ok so I'll nedd to add extra steps.

**Comment by lucacozzuto** [comment]
Done
