### ISSUE TITLE
Problem in the cluster

### ISSUE THREAD

**Issue by JMiguelRamirez** [biocorecrg/master_of_pores#21]
Hi Luca,

I have been trying to test the pipeline in the cluster, and it gives me this error when I use "$RUN python --version" with singularity 2.6.1:

`
ERROR  : Installation error, run the following commands as root to fix:
`
`
ERROR  :     sudo chown root:root /nfs/software/as/el7.2/EasyBuild/CRG/software/Singularity/2.6.1/libexec/singularity/bin/action-suid
`
`
ERROR  :     sudo chmod 4755 /nfs/software/as/el7.2/EasyBuild/CRG/software/Singularity/2.6.1/libexec/singularity/bin/action-suid
ABORT  : Retval = 255
`

And if I use singularity 3.2.1 I get this message:

`
ERROR  : Can't open /proc/self/auxv: Permission denied
`

I remember running the pipeline in the cluster one month ago and everything was working properly, do you know what can be the problem now?

Thank you very much,

**Comment by lucacozzuto** [comment]
mmm which image are you using (the latest is 0.4) and from which node?

**Comment by lucacozzuto** [comment]
I tried both nextflow node and ant-login and I had no problem...

**Comment by JMiguelRamirez** [comment]
Yes, I am using 0.4, and I was running it in the ant-login, because I can't even do qlogin, so the problem is mine, I will talk to IT.

Thanks and sorry for the inconvenience,
