### ISSUE TITLE
GraphMap2

### ISSUE THREAD

**Issue by JMiguelRamirez** [biocorecrg/master_of_pores#22]
A new realise of GraphMap is available with an option to map rnaseq data directly into genomes without the need of a gtf file. 

We could just change GraphMap to GraphMap2 (https://github.com/lbcb-sci/graphmap2). I have been testing it and it works well, I will be adding the commands into command_lines.md in case we want to include this option.

Thanks,

**Comment by lucacozzuto** [comment]
I'll keep improvements for later :)

**Comment by lucacozzuto** [comment]
Hi, I see that graphmap2 allows splice mapping like minimap2... so for consistency I would replace graphmap with graphmap2. What do you think? Can you provide me the command line?

**Comment by JMiguelRamirez** [comment]
Yes, it would make more sense to have graphmap2, and the old commands are the same.

Against transcriptome:
`graphmap2 align -r ref.fa -d reads.U2T.fastq -o out.sam  `
Against genome (splice mapping):
`graphmap2 align -x rnaseq -r ref.fa -d reads.U2T.fastq -o out.sam`

Let me know if you need anything else.

Thanks,

**Comment by lucacozzuto** [comment]
Added in the docker version 0.5 and in  https://github.com/biocorecrg/master_of_pores/commit/bcf65d682fc00f1d83cb008c6e267e0754af873b
