### ISSUE TITLE
Parallelization of basecalling and stats

### ISSUE THREAD

**Issue by lucacozzuto** [biocorecrg/master_of_pores#24]
Hi all,
I see that the guppy basecalling on our example is very slow (more than 6 hours per run with 8 CPUs). So I'm thinking to parallelize it by running on chunks (one chunk is one file). The problem will be that I'll end up with one stats file per chunk and not per run. Do you know a way to join the stats?

thanks 

Luca

**Comment by enovoa** [comment]
Thats why GPU is highly recommended for base-calling. I think that further
parallelization is prob not needed, the solution is using GPU, rather than
splitting into further chunks I think.

**Comment by lucacozzuto** [comment]
I don't know because we have 300 files so the basecalling can be speed up up to 300X. Without GPU. The only problem is joining the stats.

**Comment by lucacozzuto** [comment]
This program seems to do what we want... https://github.com/wdecoster/nanostat

**Comment by lucacozzuto** [comment]
Added this feature in https://github.com/biocorecrg/master_of_pores/commit/bcf65d682fc00f1d83cb008c6e267e0754af873b
