### ISSUE TITLE
Parameters incompatibility in guppy

### ISSUE THREAD

**Issue by ADelgadoT** [biocorecrg/master_of_pores#25]
Hi, 

To execute guppy you must either provide a kit and a flowcell or a config file (-c model.cfg). If the user specifies the three of them, the latter would be ignored. Guppy uses a specific config file based on the kit and flowcell provided by the user (guppy_basecaller --print_workflows). Using guppy alone, the user can either specify the kit and flowcell or the config file. I believe it would be great if this behaviour is the same in MoP. 

Thanks :D

**Comment by lucacozzuto** [comment]
I was not aware of this. Is this compatible with Albacore?


L

Il mer 15 gen 2020, 14:36 ADelgadoT <notifications@github.com> ha scritto:

**Comment by ADelgadoT** [comment]
I actually don't know as I've never used Albacore.

**Comment by Huanle** [comment]
command (CPU version) below will work.
the config file comes along with basecaller. 
```
guppy_basecaller -c rna_r9.4.1_70bps_hac.cfg --fast5_out -r -i ${raw_fast5_dir} --cpu_threads_per_caller ${threads} -s ${save_path} --verbose_logs --num_callers 1
```

**Comment by ADelgadoT** [comment]
Hi, 

I believe we don't need this option anymore as if the user introduces the correct kit and flowcell, the config file will be changed accordingly. If you type `guppy_basecaller --print_workflows`, all the combinations of kit+flowcell and their respective config file used by guppy will appear. 

So I propose to leave the command as it is, but we need to automatize the identification of the kit used and the flowcell to decrease the errors. We can identify the flowcell from the files generated during the sequencing. What do you think about it?

**Comment by lucacozzuto** [comment]
Everything that can reduce number of parameters is welcome! :) If you find in which file are written and we can extract them easily we can try

**Comment by ADelgadoT** [comment]
Hi Luca, 

I've found the file from which you can extract the flowcell and the kit. I'll send it to you by email. :D

**Comment by NuriaDiaz** [comment]
Hey! Following a bit in the line of these comments, I think that I've found a typo in the new EpiNano release. In lines 252 and 265 from the nanopreprocess.nf file the "--input" parameter for Guppy should be "--input_path" instead, otherwise guppy reports the following error:

"Error processing command line: 'option '--input' is ambiguous and matches '--input_file_list', and '--input_path''.
 Missing required option 'save_path'."

I still haven't figured out what's wrong with "save_path" as the command looks good to me. And so far it's running without giving further errors.

Best,
Núria

**Comment by lucacozzuto** [comment]
Hi, I think there is a bit of confusion on tool names :) Guppy is used in NanoPreprocess. I think that command line was good for older version of guppy. So I changed the command line using -i that seems conserved across different versions. You can download the latest version using git pull. https://github.com/biocorecrg/master_of_pores/commit/ae2500aa57c2278047c5665f7f2c5d898033b3dd
