### ISSUE TITLE
include threshold-based filtering of demultiplexing algorithm based on tsv, prior to fastq splitting

### ISSUE THREAD

**Issue by novoalabmember** [biocorecrg/master_of_pores#28]
Oguzhan can provide script to do so :) Thanks!

**Comment by obegik** [comment]
`#!/usr/bin/env python3
import numpy as np
__author__ = 'Hunale Liu'
import sys,gzip, bz2

usage = '''
python sort_probability_deviance.py demultixon_ouput threshold(0,1)
e.g.:
 python sort_probability_deviance.py bc1.reads.tsv.bz2 0.9
'''

if len(sys.argv) < 3:
    print (usage)
    exit(0)

def fopen (f):
    if f.endswith ('.gz'):
        fh=gzip.open(f,'r')
    elif f.endswith ('.bz2'):
        fh=bz2.open (f,'rt')
    else:
        fh = open (f,'r')
    return fh

def main ():
    out = sys.argv[1] + '.filt'
    outh = open (out,'w')
    with fopen (sys.argv[1]) as fh:
        for l in fh:
            if l.startswith ('fast5'):
                outh.write (l)
                continue
            ary = l.strip().split()
            probs = np.array(ary[-4:]).astype('float')
            probs.sort()
            dev = probs[-1] - probs[-2]
            if dev > float (sys.argv[2]):
                outh.write (l)
    outh.close()
if __name__ == "__main__":
    main()
`

**Comment by obegik** [comment]
This is what Huanle wrote as a python code to extract reads by threshold

**Comment by lucacozzuto** [comment]
Some more context will be helpful :) Which is the problem?

**Comment by obegik** [comment]
Oh sorry. This script is to extract high confidence demultiplexed reads  based on their confidence scores. It uses the demultiplexing output (tsv file) to extract the reads with higher than threshold indicated (we use 0.9 as default).

**Comment by enovoa** [comment]
actually the default is to demultiplex everything that is >0.5, i believe. we sometimes filter the tsv file to keep only those reads with probability scores of 0.9 (so high certainty that it is this barcode) However, being very stringent will discard more reads

**Comment by lucacozzuto** [comment]
consider that I'm also doing fast5 splitting. So it would be better to do this at the level of TSV generation. You can to this by adding a parameter to the demultiplexing command line (-s 0.9) 

here the help from deeplexicon:

```bash
usage: deeplexicon.py [-h] [-p PATH] [-f {multi,single}] [-c CONFIG]
                      [-s THRESHOLD] [-m MODEL] [--squiggle SQUIGGLE]
                      [--segment SEGMENT] [-b BATCH_SIZE] [-V VERSION] [-v]

DeePlexiCon - Demultiplex direct RNA reads

optional arguments:
  -h, --help            show this help message and exit
  -p PATH, --path PATH  Top path of fast5 files to dmux
  -f {multi,single}, --form {multi,single}
                        Multi or single fast5s
  -c CONFIG, --config CONFIG
                        config file
  -s THRESHOLD, --threshold THRESHOLD
                        probability threshold - 0.5 hi accuracy / 0.3 hi
                        recovery
  -m MODEL, --model MODEL
                        Trained model name to use
  --squiggle SQUIGGLE   dump squiggle data into this .tsv file
  --segment SEGMENT     dump segment data into this .tsv file
  -b BATCH_SIZE, --batch_size BATCH_SIZE
                        batch size - for single fast5s
  -V VERSION, --version VERSION
                        Prints version
  -v, --verbose         Verbose output
```

**Comment by enovoa** [comment]
Oh so the -s is still active there already in this deeplexicon version that we embeded. 
In this case we probably don’t need this additional script, we just need to make sure that we run the demultiplexing code with -s 0.9 and that in the tsv (and fastq) we only recover high confidence cases. Can you run it in the same test that you did the deeplexicon test? 
Thanks!
Eva

**Comment by lucacozzuto** [comment]
only with one model? Since the other ones were failing...

**Comment by enovoa** [comment]
Yes, just the 030 model, which should be the default and only model. For the moment I’d delete the other two from the repo. that is being fixed atm, will share with you the new fixed models as soon as we have them. thanks!
