### ISSUE TITLE
update README

### ISSUE THREAD

**Issue by enovoa** [biocorecrg/master_of_pores#3]
I would include a section of step by step installation to run masterofpores (i actually tried to include that as well in the draft by looking at the readme, but it was unclear which step is needed first, e.g. steps to install nextflow, docker, singularity, then to convert docker to singularity, to clone the repo and finally to run the workflow :)

**Comment by lucacozzuto** [comment]
Yep you are right! Basically we need only nextflow + docker or singularity. I think you don't even need to clone the repository since NF should pull the github repo for you. I'll check this option and add the procedure in the readme.

**Comment by lucacozzuto** [comment]
I made the pipeline really easy to be used. You just need either Docker or Singularity and nextflow. 
Then you can launch it simply like this:

nextflow run biocorecrg/master_of_pores -with-singularity {PARAMS}
