### ISSUE TITLE
Add tailfindr to the Docker

### ISSUE THREAD

**Issue by lucacozzuto** [biocorecrg/master_of_pores#31]
Add tailfindr to the Docker

https://github.com/adnaniazi/tailfindr

**Comment by lucacozzuto** [comment]
quite problematic installation... I got this error
configure: error: The version of hdf5 installed on your system is not sufficient. Please ensure that at least version 1.8.13 is installed
 any help?

**Comment by enovoa** [comment]
@JMiguelRamirez installed it and used it. He can advise you if he had any problems as such during the installation?

**Comment by lucacozzuto** [comment]
Yes please. I think it is a problem of centOS and its libraries... Maybe I should use another OS in the docker image

**Comment by JMiguelRamirez** [comment]
Yes, I have been using tailfindr without problems, but my version of HDF5 is 1.10.4 (https://www.hdfgroup.org/downloads/), maybe we could add a more recent version of hdf5 to the docker? With this last version, everything should work properly in centOS. Let me know if adding this is feasible or if you need any further help. Thanks

**Comment by lucacozzuto** [comment]
It was really a pain, but I managed... Added here https://github.com/biocorecrg/master_of_pores/commit/83bc42883cc94ad1fd2fa7870300960eaa81975a
