### ISSUE TITLE
new parameter for skipping fast5 demultiplexing

### ISSUE THREAD

**Issue by lucacozzuto** [biocorecrg/master_of_pores#31]

**Comment by lucacozzuto** [comment]
@enovoa which is the advantage to skip this step?

**Comment by enovoa** [comment]
that you can do a lot of things you can do with base-called fastq, and this way you would save A LOT of storage that the pipelin would create (splitted fast5 by barcode) that would occupy a lot of space. Specially now that we are still playing with different demultiplexing parameters, you really don't want to store a new combination of FAST5s. Subsetting the original fast5 into different fast5 is an easy step that can be done after executing the pipeline (if needed, not all projects even need to go back to the fast5), but in the meantime, it will avoid producing massive outputs from Nextflow. We want to have the option of keeping the output sizes of nextflow to the minimum. And only if needed, then write fast5.

**Comment by lucacozzuto** [comment]
ok. I'll try to see how to do

**Comment by enovoa** [comment]
basically you just need to demultiplex based on the fastq :) You can use the fastq_splitter.py script that comes with deeplexicon release: 
python3 fastq_splitter.py -d output.tsv -q combined.fastq -o dmux_folder/ -s sample_name

**Comment by lucacozzuto** [comment]
yep this is how it is now :) I have just to make the process demultiplexing of fast5 optional

**Comment by lucacozzuto** [comment]
Done at https://github.com/biocorecrg/master_of_pores/commit/aee7325539510f90fefc0a0bc283e544dfe3087c Please note that you need to do 
```
git checkout review
```
since I'm not touching the master repository
