### ISSUE TITLE
Testing the pipeline

### ISSUE THREAD

**Issue by lucacozzuto** [biocorecrg/master_of_pores#32]
Hi all,

please let me know who is testing the pipeline, thanks!

Luca

**Comment by lucacozzuto** [comment]
Well, since no one is helping I just launched the test on my macbook + docker and it worked :)

**Comment by enovoa** [comment]
Hi Luca, 

Morghan has tested it and I think Oguzhan is giving it a go (cc’ed both), but the person who is testing it is Huanle, who is now on holiday.

@morghan and @oguzhan - can you please share your feedback with Luca? Is there any feature missing, parameter that you would have liked to tune and couldn’t, etc?

Thanks,
Eva

**Comment by enovoa** [comment]
Hi Luca,


Sorry yes I did test it but it was a couple of months ago so I guess much has changed. I will give it a go next week and share my feedback with you :)


Thanks,

Morghan


________________________________

**Comment by lucacozzuto** [comment]
The new version of NF is amazing. If I'll have time I'll try to re-write
the pipeline in DSL-2...

Il ven 20 set 2019, 09:53 Eva Novoa <notifications@github.com> ha scritto:

> Hi Luca,
>
>
> Sorry yes I did test it but it was a couple of months ago so I guess much
> has changed. I will give it a go next week and share my feedback with you :)
>
>
> Thanks,
>
> Morghan
>
>
> ________________________________
> From: Eva Maria Novoa <evamaria.novoa@gmail.com>
> Sent: 19 September 2019 14:43:45
> To: biocorecrg/master_of_pores
> Cc: biocorecrg/master_of_pores; Subscribed; Morghan Lucas; Oguzhan Begik
> Subject: Re: [biocorecrg/master_of_pores] Testing the pipeline (#32)
>
> Hi Luca,
>
> Morghan has tested it and I think Oguzhan is giving it a go (cc’ed both),
> but the person who is testing it is Huanle, who is now on holiday.
>
> @morghan and @oguzhan - can you please share your feedback with Luca? Is
> there any feature missing, parameter that you would have liked to tune and
> couldn’t, etc?
>
> Thanks,
> Eva
>
>
> On 19 Sep 2019, at 2:40 pm, Luca Cozzuto <notifications@github.com<mailto:

**Comment by lucacozzuto** [comment]
Well, better to wait. The stable release will be done on January.



Il ven 20 set 2019, 09:53 Eva Novoa <notifications@github.com> ha scritto:

> Hi Luca,
>
>
> Sorry yes I did test it but it was a couple of months ago so I guess much
> has changed. I will give it a go next week and share my feedback with you :)
>
>
> Thanks,
>
> Morghan
>
>
> ________________________________
> From: Eva Maria Novoa <evamaria.novoa@gmail.com>
> Sent: 19 September 2019 14:43:45
> To: biocorecrg/master_of_pores
> Cc: biocorecrg/master_of_pores; Subscribed; Morghan Lucas; Oguzhan Begik
> Subject: Re: [biocorecrg/master_of_pores] Testing the pipeline (#32)
>
> Hi Luca,
>
> Morghan has tested it and I think Oguzhan is giving it a go (cc’ed both),
> but the person who is testing it is Huanle, who is now on holiday.
>
> @morghan and @oguzhan - can you please share your feedback with Luca? Is
> there any feature missing, parameter that you would have liked to tune and
> couldn’t, etc?
>
> Thanks,
> Eva
>
>
> On 19 Sep 2019, at 2:40 pm, Luca Cozzuto <notifications@github.com<mailto:
