### ISSUE TITLE
Optional deletion of the basecalled fast5 at the end of the analysis

### ISSUE THREAD

**Issue by ADelgadoT** [biocorecrg/master_of_pores#32]

**Comment by lucacozzuto** [comment]
I don't see the point of this. Files can be easily removed by the user... Can you explain me more?

**Comment by enovoa** [comment]
the point is that the user can easily forget. if its in the pipeline it is much easier for us to make sure that people will erase the files. For example, if we launch albacore to compare to guppy, for EpiNano we just want the fastq results to compare how EpiNano performs in guppy-basecalled fastq relative to albacore-basecalled fastq. But we wouldn't want to store the albacore-basecalled FAST5. So having this option equals to flexibility, while controling the size of your outputs from NextFlow.

**Comment by lucacozzuto** [comment]
This an issue not yet solved with nextflow. I'll open an issue with them but I know that is a on going question.

**Comment by lucacozzuto** [comment]
From NF chat they gave me this advice:
nextflow run pipeline.nf && rm -rf output/*/fast5_files/
