### ISSUE TITLE
Fastq files as input for NanoPreprocess

### ISSUE THREAD

**Issue by ADelgadoT** [biocorecrg/master_of_pores#33]
Hi, 

At the moment, the only input accepted by MoP - NanoPreprocess is fast5 files (raw or basecalled). The majority of users will have fastq files as input. Would it be possible to add an option to start the module with fastq files (see picture) instead of fast5? Is it feasible?

![image](https://user-images.githubusercontent.com/44808643/73166324-efa5b100-40f5-11ea-953a-4eb73b27914b.png)

Thanks :D

**Comment by lucacozzuto** [comment]
I have doubt about this. Let's see if we get more people needing this. The
risk is to make the pipeline too complex for doing simple steps. I could
also think to a new module starting from fastq.



Il lun 27 gen 2020, 11:14 ADelgadoT <notifications@github.com> ha scritto:

**Comment by enovoa** [comment]
Hi Luca, in the lab we store: i) raw fast5; ii) base-called fastq. We dont store base-called fast5 as it would be duplicated information. We usually dont need to rebasecall, but we often need to reanalyze the data using different mapping settings, etc. So hence Anna's request. It is quite essential to be able to use the module starting from fastq, and for the majority of users it will be the same.

**Comment by lucacozzuto** [comment]
Reanalyse different samples with -resume will skip the basecalling. However I'll see if to make a new module starting from fastq.

**Comment by enovoa** [comment]
following up on this as it is urgent. otherwise we cannot use the pipeline. thanks!

**Comment by lucacozzuto** [comment]
I just pushed a preliminary version (a new module) but is really really beta... if you want to play fell free :)

**Comment by ADelgadoT** [comment]
Hi, 

I tested it and it works :)

**Comment by guillaume-vares** [comment]
We would like to start Nanopreprocess directly on basecalled FastQ files because we are running Guppy independently on a different GPU server. 
What is the best way to update the nanopreprocess.nf file so that it runs directly on basecalled files?

**Comment by lucacozzuto** [comment]
Hi. In the 'review' branch we added a new module nanopreprocesSimple that starts from fastq. You can clone that branch and give it a try.

**Comment by guillaume-vares** [comment]
Hi Luca,
That’s what I thought but I wanted to make sure ☺ Thank you!
Best,
Guillaume

**Comment by cgjosephlee** [comment]
Hi Luca,
Is the 'review' branch deleted or moved? Starting from fastq files is really helpful.
Thank you.

**Comment by lucacozzuto** [comment]
Hi, that branch was highly unstable and experimental. We will likely post an upgrade soon.
