### ISSUE TITLE
re-test the 3 models for demultiplexing using updated deeplexicon code (bug fixed)

### ISSUE THREAD

**Issue by enovoa** [biocorecrg/master_of_pores#35]
Hi Luca, can you update the code to use the lates version found here? (deeplexicon.py)
The models haven't changed. Seems the issue was in the code, but this only became apparent in specific models that had larger images.  Can you pls update code and re-test the 3 models in the repo with the same test data (same as you did before)? Thanks again! Eva

https://github.com/Psy-Fer/deeplexicon

**Comment by lucacozzuto** [comment]
Hi Eva,
sure, I'll do it. Good that this is helping other your project too! :)



Luca

Il ven 31 gen 2020, 10:23 Eva Novoa <notifications@github.com> ha scritto:

**Comment by lucacozzuto** [comment]
Done at https://github.com/biocorecrg/master_of_pores/commit/95e5aab736ed923d442c24f185c8b78b13e63947
