### ISSUE TITLE
replacing epinano with newer version

### ISSUE THREAD

**Issue by lucacozzuto** [biocorecrg/master_of_pores#38]
Epinano had a problem with a script. I need to update the docker image

**Comment by lucacozzuto** [comment]
Done at https://github.com/biocorecrg/master_of_pores/commit/95e5aab736ed923d442c24f185c8b78b13e63947

**Comment by Huanle** [comment]
@lucacozzuto can you let me know the details? commands and error messages?

**Comment by lucacozzuto** [comment]
Hi @huanle is just to keep track of the change you asked me on gitter. I upgraded epinano, so it should be ok now

**Comment by lucacozzuto** [comment]
done at https://github.com/biocorecrg/master_of_pores/commit/da36853d2397c39a27c15a8457cf2b80563466d6

**Comment by enovoa** [comment]
which version have you used @lucacozzuto ?

**Comment by lucacozzuto** [comment]
the latest in Github

**Comment by enovoa** [comment]
can you please specify version number?

**Comment by lucacozzuto** [comment]
where is this information? I got the latest from github with git clone but I cannot check the version

**Comment by enovoa** [comment]
https://github.com/enovoa/EpiNano/releases <https://github.com/enovoa/EpiNano/releases>

**Comment by lucacozzuto** [comment]
no I got it from github the very latest release. The one that has the last modification 6 days ago

**Comment by enovoa** [comment]
Huanle, 
Can you confirm which VERSION is the one in the main github if one clones the repo?

**Comment by Huanle** [comment]
it is version 1.1 -- with corrected insertion frequencies.

**Comment by lucacozzuto** [comment]
But the latest is 1.2!!! Is it ok to take the latest from GitHub?

Il gio 19 mar 2020, 00:40 WHUANLEE <notifications@github.com> ha scritto:

**Comment by Huanle** [comment]
please simply clone fromthe repo, which is v1.1. v1.2 is a pre-release.

**Comment by lucacozzuto** [comment]
Ok so it is ok to do git clone?

**Comment by enovoa** [comment]
Please wait for version 1.1.1, to be in the github repo, to able to distinguish which version MoP is using.
Thanks!

**Comment by Huanle** [comment]
@lucacozzuto it is out

**Comment by lucacozzuto** [comment]
thanks! Please add me to your slack / make a channel for mop etc. since I would need some help for nanocompore etc
