### ISSUE TITLE
Add graphmap as a mapper in Nanopreprocess

### ISSUE THREAD

**Issue by ADelgadoT** [biocorecrg/master_of_pores#39]
Could we add graphmap in Nanopreprocess and Nanopreprocess_s? 

Thanks! :)

**Comment by lucacozzuto** [comment]
Hi Anna,
I just read that graphmap would not be maintained any more (they know are devoloping graphmap2). 

Do you think it makes sense to have an outdated tool in the pipeline?
```
GraphMap - A highly sensitive and accurate mapper for long, error-prone reads http://www.nature.com/ncomms/2016/160415/ncomms11307/full/ncomms11307.html Note: This was the original repository which will no longer be officially maintained. Please use the new official repository here: https://github.com/lbcb-sci/graphmap2
```

https://github.com/isovic/graphmap

Luca

**Comment by enovoa** [comment]
Hi Luca, it does for us, as we currently have benchmarked with one for many datasets.
We are not suggesting to exclude graphmap2, but to include graphmap to be able to have all the datasets processed in the way that we know it works, at least for the moment.
Thanks!
Eva

**Comment by lucacozzuto** [comment]
fine

**Comment by lucacozzuto** [comment]
done at https://github.com/biocorecrg/master_of_pores/commit/3c0400afd21a9f86e568027e8e9350f0f4fb5bab
