### ISSUE TITLE
deeplexicon - old model + old script / new model + new script

### ISSUE THREAD

**Issue by enovoa** [biocorecrg/master_of_pores#41]
Hi Luca, 

If you could please update MoP deeplexicon such that:

1) Old script and model are used together as option #1 (i.e. when model 030 is requested):
https://github.com/novoalab/deeplexicon_only_for_model030 
Here you can find the script and model for old version

2) New script and new model are used together as option #2 (i.e. when model final is requested): both script and new model are the ones currently present in github repo (which are the ones also currently used by MoP)

Thanks,
Eva

**Comment by lucacozzuto** [comment]
solved in https://github.com/biocorecrg/master_of_pores/commit/923a0677b0752b9d077c4a06418f472d78c76d63
