### ISSUE TITLE
Counting command with htseq-count in NanoPreprocess and NanoPreprocessSimple

### ISSUE THREAD

**Issue by ADelgadoT** [biocorecrg/master_of_pores#43]
Hola, 

In both NanoPreprocess and NanoPreprocess simple, there are these lines to perform feature counting with htseq (gene level):

```
samtools view ${bamfile} |htseq-count -f sam - ${anno} -o ${idfile}.sam > ${idfile}.count
awk '{gsub(/XF:Z:/,"",\$NF); print \$1"\t"\$NF}' ${idfile}.sam | grep -v '__' > ${idfile}.assigned
rm ${idfile}.sam
```
1. The already existing parameter counter_opt should be included in the command:  
```
samtools view ${bamfile} |htseq-count -f sam - ${anno} **${counter_opt}** -o ${idfile}.sam > ${idfile}.count
awk '{gsub(/XF:Z:/,"",\$NF); print \$1"\t"\$NF}' ${idfile}.sam | grep -v '__' > ${idfile}.assigned
rm ${idfile}.sam
```
2. Would it be possible to also report ambiguous assignations? In other words, also report those entries with '__' (thus, eliminating the grep -v)? Or could we make an option for that? 
```
samtools view ${bamfile} |htseq-count -f sam - ${anno} **${counter_opt}** -o ${idfile}.sam > ${idfile}.count
awk '{gsub(/XF:Z:/,"",\$NF); print \$1"\t"\$NF}' ${idfile}.sam | **grep -v '__'** > ${idfile}.assigned
rm ${idfile}.sam
```

Thanks!

**Comment by lucacozzuto** [comment]
Hi! Thanks for pointing out the missing parameter. I'll add it right now.  BTW you should have a count folder with the results from htseq... Can you check them? PS: I'm also on slack.

**Comment by lucacozzuto** [comment]
Added conter_opt at https://github.com/biocorecrg/master_of_pores/commit/2e75618b975de298c2d5bf73a493dd83e1817b57
