### ISSUE TITLE
add cram

### ISSUE THREAD

**Issue by enovoa** [biocorecrg/master_of_pores#46]
for generating IGV visualizations

**Comment by lucacozzuto** [comment]
I would need the command lines :) and also if we want to add some downsampling

**Comment by enovoa** [comment]
Can we add Toni in this issue? He did it, not me....

**Comment by lucacozzuto** [comment]
@toniher can you help me on this, please?

**Comment by toniher** [comment]
Code used here: https://github.com/biocorecrg/covid/blob/master/scripts/procCRAM.sh

**Comment by lucacozzuto** [comment]
Added at https://github.com/biocorecrg/master_of_pores/commit/1703a4d8c918dd2b0500c5c2e579083418a4a8b7
