### ISSUE TITLE
NanoIsoform module - create and add two softwares to assign which read belongs to which isoform

### ISSUE THREAD

**Issue by enovoa** [biocorecrg/master_of_pores#47]
1. Include **npTranscript** to assign which readID corresponds to each mRNA based on a gtf
https://github.com/lachlancoin/npTranscript
** Used for SARS-CoV2

2. Include **FLAIR** to assign which readID corresponds to each mRNA based on a gtf
https://github.com/BrooksLabUCSC/flair

**Comment by enovoa** [comment]
This way we can run NanoMod and NanoTail directly on per-transcript files, rather than per-genome files

**Comment by lucacozzuto** [comment]
Hi! I would need some command lines :) Can we discuss it on Slack?

**Comment by ADelgadoT** [comment]
For **npTranscript**
1. Change path to npTranscript in files: `scripts/run.sh` and `scripts/run_extract_cluster.sh`
2. Change path to the bam file(s) to analyse + reference file + coordinates file + output directory in `scripts/run_example.sh` 
3. Run `Rscript run_example`

I believe only one process is needed for the whole thing. **Input files:**
1. Bam file(s) - it can process one or more bam files at the same time
2. Reference - fasta format
3. Coordinates file - already generated by developers for SARS-Cov2 (npTranscript/data/SARS-Cov2/Coordinates.csv) - Example format below:
```
Name,Type,Minimum,Maximum,Length,Direction,gene
UTR,5'UTR,1,13,13,forward,none
leader,leader,14,75,62,forward,leader
UTR,5'UTR,76,265,189,forward,none
ORF1ab gene,gene,266,21555,21290,forward,ORF1ab
S gene,gene,21563,25384,3822,forward,S
ORF3a gene,gene,25393,26220,828,forward,ORF3a
E gene,gene,26245,26472,228,forward,E
M gene,gene,26523,27191,669,forward,M
ORF6 gene,gene,27202,27387,186,forward,ORF6
ORF7a gene,gene,27394,27759,366,forward,ORF7a
ORF8 gene,gene,27894,28259,366,forward,ORF8
N gene,gene,28274,29533,1260,forward,N
ORF10 gene,gene,29558,29674,117,forward,ORF10
UTR,3'UTR,29675,29893,219,forward,none
```
**Output files:**
npTranscript will generate an output directory - specified by user in `scripts/run_example.sh`
I would output:
1. File: 0readToCluster.txt.gz - found in the output directory. It contains the raw results 
2. Folder 'clusters' - found inside the output directory. It contains separate files (one per cluster) with the processed results - reads ID belonging to that specific cluster. 

There is also a way to plot the results - shall we plot them? Or shall the user do it on his/her own? @enovoa

**Comment by lucacozzuto** [comment]
mmm I don't like the custom input files like this... can we use a standard format like GTF, GFF, BED? I could try then to make the custom format for the program.

**Comment by enovoa** [comment]
This is what the code uses unfortunately… perhaps open an issue in repo of npTranscript asking if they have a script for conversion of gtf to their format of input?

**Comment by lucacozzuto** [comment]
I think is quite easy to make it. I'll do it
