### ISSUE TITLE
Outputing NanoPolish results from NanoMod

### ISSUE THREAD

**Issue by ADelgadoT** [biocorecrg/master_of_pores#48]
The output from the process `cat_collapsed_nanopolish` - one per sample - should be part of the NanoMod's output. These results should be place in a new folder called 'Nanopolish'. 

Thus, the NanoMod results folder structure should be: Epinano, Tombo, Nanocomp and Nanopolish. 

Thanks! :)

**Comment by lucacozzuto** [comment]
Done at https://github.com/biocorecrg/master_of_pores/commit/e0f7bdc2bfbeea606564d291a937f716f3cf535c
