### ISSUE TITLE
NanoMod running tombo through modPhred de_novo

### ISSUE THREAD

**Issue by lpryszcz** [biocorecrg/master_of_pores#49]
Hi @lucacozzuto, I've implemented tombo so it can process multi_fast5 files and output results directly to BAM. @enovoa wanted to incorporate that inside NanoMod. How can I proceed?

**Comment by lucacozzuto** [comment]
wow this will be a major improvement and quite some change of the code in nanomod pipeline. I don't know if we need BAM output. Can we talk about this on slack?

**Comment by enovoa** [comment]
This issue can be closed for the moment
