### ISSUE TITLE
Using guppy GPU basecaller server on cluster

### ISSUE THREAD

**Issue by callumparr** [biocorecrg/master_of_pores#50]
Is it possible to modify nextflow options to accept --port and use a GPU installed on another node on cluster? 

I tried local install in my directory on cluster where I installed master of pores, guppy gpu and had issues with not being able to install CUDA Drivers first so I reverted to guppy-cpu. Howvver I do have Tesla GPU card on another node and I can use the cpu version of guppy as client and --port flag.

**Comment by lucacozzuto** [comment]
Hi. I think the easiest way is to do the peak calling in the node with GPU card... (if you have a cluster).
  
You can change the nextflow.global.config file and add
```
  withLabel: basecall_gpus {
        queue = 'NODE_NAME_WITH_GPU' 
        container = 'biocorecrg/mopbasecall:0.1'
        cpus = 2 
        maxForks = 1
        containerOptions = { workflow.containerEngine == "singularity" ? '--nv':
           ( workflow.containerEngine == "docker" ? '-u $(id -u):$(id -g) --gpus all': null ) } 
  } 
 ```

**Comment by callumparr** [comment]
I have not managed to get this working as of yet because there is issue that the GPU not being accessible from the node where my data and master of pores is installed

**Comment by callumparr** [comment]
Anyway I had GPU on my local machine and got most of it working on CPU and now I tried GPU in the params.cfg but there seems to be issue with Docker API versions 

Sorry is there easier way around this without updating docker . I am not sure how this is done easily. 

`

kit                       : SQK-RNA001
flowcell                  : FLO-MIN106
fast5                     : /home/minion/master_of_pores/NanoPreprocess/../data/multifast/*.fast5
reference                 : /home/minion/master_of_pores/NanoPreprocess/../anno/curlcake_constructs.fasta.gz
annotation                : 

ref_type                  : transcriptome
seq_type                  : RNA

output                    : /home/minion/master_of_pores/NanoPreprocess/output
qualityqc                 : 7
granularity               : 

basecaller                : guppy
basecaller_opt            : 
GPU                       : ON
demultiplexing            :  
demultiplexing_opt        : -m pAmps-final-actrun_newdata_nanopore_UResNet20v2_model.030.h5 

filter                    : 
filter_opt                : 
mapper                    : minimap2
mapper_opt                : -uf -k14
map_type                  : unspliced

counter                   : YES
counter_opt               : 

email                     : callum.parr@riken.jp
executor >  local (2)
[8d/bfb09c] process > testInput             [100%] 1 of 1 ✔
[0a/703f55] process > baseCalling           [  0%] 0 of 1
executor >  local (2)
[8d/bfb09c] process > testInput             [100%] 1 of 1 ✔
[0a/703f55] process > baseCalling           [100%] 1 of 1, failed: 1 ✘
[-        ] process > concatenateFastQFiles -
[-        ] process > QC                    -
[-        ] process > fastQC                -
[-        ] process > mapping               -
[-        ] process > counting              -
[-        ] process > joinCountQCs          -
[-        ] process > alnQC                 -
[-        ] process > joinAlnQCs            -
executor >  local (2)
[8d/bfb09c] process > testInput             [100%] 1 of 1 ✔
[0a/703f55] process > baseCalling           [100%] 1 of 1, failed: 1 ✘
[-        ] process > concatenateFastQFiles -
[-        ] process > QC                    -
[-        ] process > fastQC                -
[-        ] process > mapping               -
[-        ] process > counting              -
[-        ] process > joinCountQCs          -
[-        ] process > alnQC                 -
[-        ] process > joinAlnQCs            -
[-        ] process > alnQC2                -
[-        ] process > multiQC               -
Sending the email to callum.parr@riken.jp
MultiFast5 files detected!
Error executing process > 'baseCalling (guppy-multifast-0)'

Caused by:
  Process `baseCalling (guppy-multifast-0)` terminated with an error exit status (1)

Command executed:

  export LD_LIBRARY_PATH="/usr/local/nvidia/lib:/usr/local/nvidia/lib64:/.singularity.d/libs"
  guppy_basecaller -x "cuda:0" --flowcell FLO-MIN106 --kit SQK-RNA001 --fast5_out  --input_path ./ --save_path ./0_out --cpu_threads_per_caller 1  --num_callers  2 
  cat 0_out/*.fastq  | awk '{if (NR%4==2) gsub("U","T"); print}'  >> 0.fastq
  rm 0_out/*.fastq
  gzip 0.fastq

Command exit status:
  1

Command output:
  (empty)

Command error:
  "--gpus" requires API version 1.40, but the Docker daemon API version is 1.39

Work dir:
  /home/minion/master_of_pores/NanoPreprocess/work/0a/703f55bb3bd8b1be2e01b2572a06af

Tip: you can replicate the issue by changing to the process work dir and entering the command `bash .command.run`
Failed to invoke `workflow.onComplete` event handler

 -- Check script 'nanopreprocess.nf' at line: 673 or see '.nextflow.log' file for more details
`

**Comment by lucacozzuto** [comment]
I strongly recommend to use singularity. However we tested docker too and it worked. You might want to get in touch with people of docker for checking the problem (version?)

**Comment by callumparr** [comment]
OK I will try singularity as its looking I will have to go down this option on our HPC cluster as well
