### ISSUE TITLE
Failure at first step on test multi_fast5 with nano preprocess

### ISSUE THREAD

**Issue by callumparr** [biocorecrg/master_of_pores#51]
I am guessing this failure on test fast5 script is because of the docker image pull fail error (because lack of space) or also another error in addition? 

`
executor >  local (1)
[45/f2daad] process > testInput             [  0%] 0 of 1
[-        ] process > baseCalling           -
[-        ] process > concatenateFastQFiles -
[-        ] process > QC                    -
[-        ] process > fastQC                -
[-        ] process > mapping               -
[-        ] process > alnQC                 -
[-        ] process > joinAlnQCs            -
[-        ] process > alnQC2                -
[-        ] process > multiQC               -

Error executing process > 'testInput (multifast5_1.fast5)'

Caused by:
  Process `testInput (multifast5_1.fast5)` terminated with an error exit status (125)

Command executed:

  fast5_type.py multifast5_1.fast5

Command exit status:
  125

Command output:
  (empty)

Command error:
  2a7e8e5f27b9: Pull complete
  04920849e9bb: Pull complete
  6a4fbb1ca9cf: Pull complete
  4b1ed5a54e49: Pull complete
  60f68c6a8169: Pull complete
  dc77bc6ebd0d: Pull complete
  f57ce47e580e: Pull complete
  066dec84918b: Pull complete
  a4a559aaec8e: Pull complete
  b17a80a838fb: Pull complete
  fe3438c68c1d: Pull complete
  085e113f5f7b: Pull complete
  2ee85af3b452: Pull complete
  da66a89a03a7: Pull complete
  3ac11ece5aab: Pull complete
  1394acde2a81: Pull complete
  5edeeaeadef1: Pull complete
executor >  local (1)
[45/f2daad] process > testInput             [100%] 1 of 1, failed: 1 ✘
[-        ] process > baseCalling           -
[-        ] process > concatenateFastQFiles -
[-        ] process > QC                    -
[-        ] process > fastQC                -
[-        ] process > mapping               -
[-        ] process > alnQC                 -
[-        ] process > joinAlnQCs            -
[-        ] process > alnQC2                -
[-        ] process > multiQC               -
Error executing process > 'testInput (multifast5_1.fast5)'

Caused by:
  Process `testInput (multifast5_1.fast5)` terminated with an error exit status (125)

Command executed:

  fast5_type.py multifast5_1.fast5

Command exit status:
  125

Command output:
  (empty)

Command error:
  2a7e8e5f27b9: Pull complete
  04920849e9bb: Pull complete
  6a4fbb1ca9cf: Pull complete
  4b1ed5a54e49: Pull complete
  60f68c6a8169: Pull complete
  dc77bc6ebd0d: Pull complete
  f57ce47e580e: Pull complete
  066dec84918b: Pull complete
  a4a559aaec8e: Pull complete
  b17a80a838fb: Pull complete
  fe3438c68c1d: Pull complete
  085e113f5f7b: Pull complete
  2ee85af3b452: Pull complete
  da66a89a03a7: Pull complete
  3ac11ece5aab: Pull complete
  1394acde2a81: Pull complete
  5edeeaeadef1: Pull complete
  7bd9a067625a: Pull complete
  0c4eda9cb877: Pull complete
  c90562b9f2fb: Pull complete
  0d99117c925b: Pull complete
  d2ca7993095d: Pull complete
  b9c7d7841787: Pull complete
  e88edb3ef41e: Pull complete
  7fc4344ebe5f: Pull complete
  ab1bb2fe7ff8: Pull complete
  deb205b3d374: Pull complete
  02aad2ada98a: Pull complete
  57ac619f75d7: Pull complete
  6423f83b264a: Pull complete
  e169bd05d54b: Pull complete
  0b26257ae23c: Pull complete
  006f65565cc9: Pull complete
  a3f764d8cc76: Pull complete
  81b3f1e98e83: Pull complete
  ecd0408b2ac0: Pull complete
  66ed8d7a97e2: Pull complete
  d01e09ff47c2: Pull complete
  fb7da15c94b4: Pull complete
  6d940d18076d: Pull complete
  b5f5510b3b2f: Pull complete
  2dd6d6a811a1: Pull complete
  7657715f5aa7: Pull complete
  d4f3db9950d8: Pull complete
  a60004f1af68: Pull complete
  c9da3210b8d4: Pull complete
  4da4ec478b80: Pull complete
  6615114631c9: Pull complete
  docker: failed to register layer: no space left on device.
  See 'docker run --help'.

Work dir:
  /home/callum/master_of_pores/NanoPreprocess/work/45/f2daadd2d54ce7fc6a5021bf6272ae

Tip: you can try to figure out what's wrong by changing to the process work dir and showing the script file named `.command.sh`
`

**Comment by lucacozzuto** [comment]
I think the error is due to the missing image.

**Comment by callumparr** [comment]
> I think the error is due to the missing image.

Confirm after cleaning up docker system image was pulled and first step passed.
