### ISSUE TITLE
workflow.onComplete not invoked ; carrier over form older version? 

### ISSUE THREAD

**Issue by callumparr** [biocorecrg/master_of_pores#52]
Every thing but the last step using `workflow.onComplete` worked. 

Does this delete the work directory once all files are in the output directory?

`
(base) callum@d403:~/master_of_pores/NanoPreprocess$ nextflow run nanopreprocess.nf -with-docker -resume
N E X T F L O W  ~  version 20.01.0
Launching `nanopreprocess.nf` [maniac_hopper] - revision: b92a6e1b7e
╔╦╗┌─┐┌─┐┌┬┐┌─┐┬─┐  ┌─┐┌─┐  ╔═╗╔═╗╦═╗╔═╗╔═╗
║║║├─┤└─┐ │ ├┤ ├┬┘  │ │├┤   ╠═╝║ ║╠╦╝║╣ ╚═╗
╩ ╩┴ ┴└─┘ ┴ └─┘┴└─  └─┘└    ╩  ╚═╝╩╚═╚═╝╚═╝
                                                                                       
====================================================
BIOCORE@CRG Preprocessing of Nanopore direct RNA - N F  ~  version 0.1
====================================================

kit                       : SQK-RNA001
flowcell                  : FLO-MIN106
fast5                     : /home/callum/master_of_pores/NanoPreprocess/../data/multifast/*.fast5
reference                 : /home/callum/master_of_pores/NanoPreprocess/../anno/curlcake_constructs.fasta.gz
annotation                : 

ref_type                  : transcriptome
seq_type                  : RNA

output                    : /home/callum/master_of_pores/NanoPreprocess/output
qualityqc                 : 7
granularity               : 

basecaller                : guppy
basecaller_opt            : 
GPU                       : OFF
demultiplexing            :  
demultiplexing_opt        : -m pAmps-final-actrun_newdata_nanopore_UResNet20v2_model.030.h5 

filter                    : 
filter_opt                : 
mapper                    : minimap2
mapper_opt                : -uf -k14
map_type                  : unspliced

counter                   : NO
counter_opt               : 

email                     : callumjcparr@gmail.com
Pipeline BIOCORE@CRG Master of Pore completed!
Started at  2020-04-21T17:13:53.337+09:00   [100%] 1 of 1, cached: 1 ✔
Finished at 2020-04-21T17:21:04.666+09:00   [100%] 1 of 1 ✔
Time elapsed: 7m 11s> concatenateFastQFiles [100%] 1 of 1 ✔
Execution status: OK> QC                    [100%] 1 of 1 ✔
executor >  local (9)
[8a/70d400] process > testInput             [100%] 1 of 1, cached: 1 ✔
[35/a35774] process > baseCalling           [100%] 1 of 1 ✔
[5b/3c31c8] process > concatenateFastQFiles [100%] 1 of 1 ✔
[d6/1323cb] process > QC                    [100%] 1 of 1 ✔
[1f/091712] process > fastQC                [100%] 1 of 1 ✔
[5d/c24a4f] process > mapping               [100%] 1 of 1 ✔
[b6/00650a] process > alnQC                 [100%] 1 of 1 ✔
[3c/e5652d] process > joinAlnQCs            [100%] 1 of 1 ✔
[f3/8275bf] process > alnQC2                [100%] 1 of 1 ✔
[59/a1011d] process > multiQC               [100%] 1 of 1 ✔
Failed to invoke `workflow.onComplete` event handler

 -- Check script 'nanopreprocess.nf' at line: 673 or see '.nextflow.log' file for more details
Completed at: 21-Apr-2020 17:21:04
Duration    : 7m 11s
CPU hours   : 1.3 (0.8% cached)
Succeeded   : 9
Cached      : 1

`

**Comment by lucacozzuto** [comment]
Hi,
no the manual folder has to be removed manually. The failing on.Complete is
something strange...

Luca

Il mar 21 apr 2020, 10:32 callumparr <notifications@github.com> ha scritto:

**Comment by callumparr** [comment]
> Hi, no the manual folder has to be removed manually. The failing on.Complete is something strange... Luca Il mar 21 apr 2020, 10:32 callumparr <notifications@github.com> ha scritto:
> […](#)

maybe it is the email. I put my email in param.config but if I remove seems to not cause this issue. I was unsure what is correct way to set this email notification up.

**Comment by lucacozzuto** [comment]
So I think it cannot trigger the mail... for this it failed.
