### ISSUE TITLE
Issues with newer guppy installs 

### ISSUE THREAD

**Issue by callumparr** [biocorecrg/master_of_pores#53]
Ran into few issues on cluster so now installing master_of_pores on local ubuntu box. There is some ambiguity in the flags between versions maybe. It is best to stick with v3.1.5 that is in the documents? 

`
Error executing process > 'baseCalling (guppy-multifast-0)'

Caused by:
  Process `baseCalling (guppy-multifast-0)` terminated with an error exit status (255)

Command executed:

  guppy_basecaller  --flowcell FLO-MIN106 --kit SQK-RNA001 --fast5_out  --input ./ --save_path ./0_out --cpu_threads_per_caller 1  --num_callers  8 
  cat 0_out/*.fastq  | awk '{if (NR%4==2) gsub("U","T"); print}'  >> 0.fastq
  rm 0_out/*.fastq
  gzip 0.fastq

Command exit status:
  255

Command output:
  (empty)

Command error:
  WARNING: Your kernel does not support swap limit capabilities or the cgroup is not mounted. Memory limited without swap.
  Error processing command line: 'option '--input' is ambiguous and matches '--input_file_list', and '--input_path''.
  Missing required option 'save_path'.

Work dir:
  /home/minion/master_of_pores/NanoPreprocess/work/e1/0978b547b3e9214e0baa40c00bfa5d

Tip: view the complete command output by changing to the process work dir and entering the command `cat .command.out`
`

**Comment by lucacozzuto** [comment]
Hi, which version are you using? I see from:
```
Error processing command line: 'option '--input' is ambiguous and matches '--input_file_list', and '--input_path''.
Missing required option 'save_path'.
```
that this version has a different command-line/interface. If you need this particular version you might want to change the command line in the NF code...

**Comment by callumparr** [comment]
I was installing v3.5.2 but then something that is a little newer than 3.1.5. 

I was looking at help for guppy and it wasn't so obvious why it couldn't handle the current command submitted by nanopreprocessing.nf. Both use input_path and save_path similarly

**Comment by lucacozzuto** [comment]
This is the command line currently in use:
```
			guppy_basecaller ${gpu_cmd} --flowcell ${params.flowcell} --kit ${params.kit} --fast5_out ${basecaller_opt} --input ${infolder} --save_path ./${idfile}_out --cpu_threads_per_caller 1  --num_callers  ${task.cpus} 
```
I think that just changing --input with --input_path would fix this... let me know

**Comment by callumparr** [comment]
That worked. Thank you. It seems to handle the the differences in guppy output structures without any further modification.

**Comment by lucacozzuto** [comment]
I will double-check if it works also with the older version and I'll modify the code accordingly. Thanks for your report!
