### ISSUE TITLE
Exceed minimum available memory 

### ISSUE THREAD

**Issue by callumparr** [biocorecrg/master_of_pores#54]
Sorry for so many questions. I am having issue with memory allowance on by machine. Its got 16GB (14GB available) RAM but the mapping and samtools step require 20GB.I have a swapfile of around 20GB on hard drive that can also be used . Do you know if this requirement can be relaxed?  

`
email                     :
executor >  local (4)
[e6/7ec40b] process > testInput             [100%] 1 of 1, cached: 1 ✔
[b5/1ff570] process > baseCalling           [100%] 1 of 1 ✔
[31/e100b7] process > concatenateFastQFiles [100%] 1 of 1 ✔
[44/2fc2ed] process > QC                    [100%] 1 of 1 ✔
executor >  local (4)
[e6/7ec40b] process > testInput             [100%] 1 of 1, cached: 1 ✔
[b5/1ff570] process > baseCalling           [100%] 1 of 1 ✔
[31/e100b7] process > concatenateFastQFiles [100%] 1 of 1 ✔
[44/2fc2ed] process > QC                    [100%] 1 of 1 ✔
[-        ] process > fastQC                -
[54/a91817] process > mapping               [200%] 2 of 1, failed: 2
[-        ] process > alnQC                 -
[-        ] process > joinAlnQCs            -
[-        ] process > alnQC2                -
[-        ] process > multiQC               -
WARN: Killing pending tasks (1)
Error executing process > 'mapping (minimap2-multifast)'

Caused by:
  Process requirement exceed available memory -- req: 20 GB; avail: 15.6 GB

Command executed:

  minimap2 -t 8 -ax map-ont -uf -k14  curlcake_constructs.fasta.gz multifast.fq.gz | samtools view -@ 8 -F4 -hSb - > reads.mapped.bam
  samtools sort -@ 8 -o multifast.minimap2.sorted.bam reads.mapped.bam
  rm reads.mapped.bam

Command exit status:
  -

Command output:
  (empty)

Work dir:
  /home/minion/master_of_pores/NanoPreprocess/work/54/a918172258caa3d3ec6ee9fb6e292e

Tip: you can replicate the issue by changing to the process work dir and entering the command `bash .command.run`

`

**Comment by lucacozzuto** [comment]
the configuration is in nextflow.global.config
you can change reducing the amount of RAM required in the section **big_mem_cpus**
```
  withLabel: big_mem_cpus {
        cpus = 8
        memory = '20G' -> memory = '14G' 
  }
```
