### ISSUE TITLE
GPU fast5 loaded sequentially in separate run cmd

### ISSUE THREAD

**Issue by callumparr** [biocorecrg/master_of_pores#57]
I am now running through real data now. 

During basecalling, there is a fast5 files are loaded into a common separately and sequentially. Is this correct and if so is there a reason for this?

**Comment by lucacozzuto** [comment]
Are you using GPU? Is your granularity parameter empty?

**Comment by callumparr** [comment]
As yes I am using GPU. I did not set granularity as I thought this was for no. of reads reads more than files. I am dealing with multi_fast5 files.

**Comment by lucacozzuto** [comment]
This is the number of files either they are sequences or multifast5 files. I automatically change this parameter when using GPU = "YES" to a very large number. So I don't get what is happening. Can you try to use granularity=1000000 ?

**Comment by callumparr** [comment]
Cool I will set this. Makes sense.

**Comment by callumparr** [comment]
It seems setting granularity to something very large didn't stop it loading one multi_fast5 at a time into guppy . In any case, I guess its not so much of an issue.

**Comment by lucacozzuto** [comment]
Yes but is a good reminder :) Let me check

**Comment by lucacozzuto** [comment]
is this happening also with CPUs? Are you using the review branch or the master branch?

**Comment by callumparr** [comment]
I am with the master branch. Thats something I didnt check because that time I was just running through it with the supplied single file in data. But I will confirm that the default 4000 read loading is correct.

**Comment by callumparr** [comment]
with two discoverable multi_fast5 files in input directory its still loading in 1 file for guppy basecaller with CPU mode.

`
ONT Guppy basecalling software version 3.5.2+5b7a51b, client-server API version 1.1.0
config file:        /home/minion/master_of_pores/NanoPreprocess/bin/ont-guppy/data/rna_r9.4.1_70bps_hac.cfg
model file:         /home/minion/master_of_pores/NanoPreprocess/bin/ont-guppy/data/template_rna_r9.4.1_70bps_hac.jsn
input path:         ./
save path:          ./1_out
chunk size:         2000
chunks per runner:  512
records per file:   4000
num basecallers:    8
cpu mode:           ON
threads per caller: 1

Found 1 fast5 files to process.
Init time: 6340 ms

0%   10   20   30   40   50   60   70   80   90   100%
|----|----|----|----|----|----|----|----|----|----|
*************************

`

`
kit                       : SQK-RNA001
flowcell                  : FLO-MIN106
fast5                     : /home/minion/*.fast5
reference                 : /home/minion/ont_tutorial_transcriptome/Analysis/ReferenceData/Mus_musculus.GRCm38.cdna.all.fa
annotation                : 

ref_type                  : transcriptome
seq_type                  : RNA

output                    : /home/minion/master_of_pores/NanoPreprocess/test3
qualityqc                 : 7
granularity               : 

basecaller                : guppy
basecaller_opt            : 
GPU                       : OFF
demultiplexing            :  
demultiplexing_opt        : -m pAmps-final-actrun_newdata_nanopore_UResNet20v2_model.030.h5 

filter                    : 
filter_opt                : 
mapper                    : minimap2
mapper_opt                : -uf -k14
map_type                  : unspliced

counter                   : YES
counter_opt               : 

email                     : callum.parr@riken.jp
executor >  local (2)
[cc/89265a] process > testInput             [100%] 1 of 1 ✔
[5f/1c9ea0] process > baseCalling           [  0%] 0 of 2
[-        ] process > concatenateFastQFiles -
[-        ] process > QC                    -
[-        ] process > fastQC                -
[-        ] process > mapping               -
[-        ] process > counting              -
[-        ] process > joinCountQCs          -
[-        ] process > alnQC                 -
[-        ] process > joinAlnQCs            -
[-        ] process > alnQC2                -
[-        ] process > multiQC               -
Sending the email to callum.parr@riken.jp
MultiFast5 files detected!

`

**Comment by lucacozzuto** [comment]
This will be solved in the DSL2 version (soon)

**Comment by callumparr** [comment]
Look forward
