### ISSUE TITLE
Issue with live basecall fast5 for tailfindr

### ISSUE THREAD

**Issue by callumparr** [biocorecrg/master_of_pores#58]
I have some fast5 that were originally outputted to pass and fail with MinKNOW livebasecalling. I am unsure if squiggles/events were written on the fast5 or the fast5 were just moves to pass or fail directories. 

<img width="851" alt="Screen Shot 2020-04-26 at 5 39 31 PM" src="https://user-images.githubusercontent.com/41637575/80313818-50bc4e00-87e5-11ea-8da3-f44c9a28d22f.png">

I rebasecalled the fast5 files through master of pores NanoPreprocess which runs smoothly. 

I am unsure what the basecall group should be as master of pores should overwrite previous squiggles? 

`
executor >  local (2)
[5b/4022d8] process > check_reference            [100%] 1 of 1, cached: 1 ✔
[d7/f72177] process > tailfindr                  [  0%] 0 of 574
[-        ] process > filter_bam                 [  0%] 0 of 1
[-        ] process > tail_nanopolish            -
[-        ] process > collect_nanopolish_results -
[-        ] process > collect_tailfindr_results  -
[-        ] process > join_results               -
Sending the email to callum.parr@riken.jp
Error executing process > 'tailfindr (Day1_01_DRS-FAL87078_pass_6dc8999c_347)'

Caused by:
  Missing output file(s) `*_findr.csv` expected by process `tailfindr (Day1_01_DRS-FAL87078_pass_6dc8999c_347)`

Command executed:

  R --slave -e "library(tailfindr); find_tails(fast5_dir = './' , save_dir = './', , csv_filename = 'Day1_01_DRS-FAL87078_pass_6dc8999c_347_findr.csv', num_cores = 4)"

Command exit status:
executor >  local (2)
[5b/4022d8] process > check_reference            [100%] 1 of 1, cached: 1 ✔
[ec/9055b7] process > tailfindr                  [  0%] 1 of 574, failed: 1
[-        ] process > filter_bam                 [  0%] 0 of 1
[-        ] process > tail_nanopolish            -
[-        ] process > collect_nanopolish_results -
[-        ] process > collect_tailfindr_results  -
[-        ] process > join_results               -
Sending the email to callum.parr@riken.jp
Error executing process > 'tailfindr (Day1_01_DRS-FAL87078_pass_6dc8999c_347)'

Caused by:
  Missing output file(s) `*_findr.csv` expected by process `tailfindr (Day1_01_DRS-FAL87078_pass_6dc8999c_347)`

Command executed:

  R --slave -e "library(tailfindr); find_tails(fast5_dir = './' , save_dir = './', , csv_filename = 'Day1_01_DRS-FAL87078_pass_6dc8999c_347_findr.csv', num_cores = 4)"

Command exit status:
  0

Command output:
  ────────────────────────────────────────────────────────────────────────────────
  ── Started tailfindr (version 0.1.0) ───────────────────────────────────────────
executor >  local (2)
[5b/4022d8] process > check_reference            [100%] 1 of 1, cached: 1 ✔
[ec/9055b7] process > tailfindr                  [  0%] 1 of 574, failed: 1
[-        ] process > filter_bam                 [  0%] 0 of 1
[-        ] process > tail_nanopolish            -
[-        ] process > collect_nanopolish_results -
[-        ] process > collect_tailfindr_results  -
[-        ] process > join_results               -
Sending the email to callum.parr@riken.jp
Error executing process > 'tailfindr (Day1_01_DRS-FAL87078_pass_6dc8999c_347)'

Caused by:
  Missing output file(s) `*_findr.csv` expected by process `tailfindr (Day1_01_DRS-FAL87078_pass_6dc8999c_347)`

Command executed:

  R --slave -e "library(tailfindr); find_tails(fast5_dir = './' , save_dir = './', , csv_filename = 'Day1_01_DRS-FAL87078_pass_6dc8999c_347_findr.csv', num_cores = 4)"

Command exit status:
  0

Command output:
executor >  local (2)
[5b/4022d8] process > check_reference            [100%] 1 of 1, cached: 1 ✔
[d7/f72177] process > tailfindr                  [  0%] 1 of 573, failed: 1
[-        ] process > filter_bam                 [  0%] 0 of 1
[-        ] process > tail_nanopolish            -
[-        ] process > collect_nanopolish_results -
[-        ] process > collect_tailfindr_results  -
[-        ] process > join_results               -
Sending the email to callum.parr@riken.jp
WARN: Killing pending tasks (1)
Error executing process > 'tailfindr (Day1_01_DRS-FAL87078_pass_6dc8999c_347)'

Caused by:
  Missing output file(s) `*_findr.csv` expected by process `tailfindr (Day1_01_DRS-FAL87078_pass_6dc8999c_347)`

Command executed:

  R --slave -e "library(tailfindr); find_tails(fast5_dir = './' , save_dir = './', , csv_filename = 'Day1_01_DRS-FAL87078_pass_6dc8999c_347_findr.csv', num_cores = 4)"

Command exit status:
  0

Command output:
  ────────────────────────────────────────────────────────────────────────────────
  ── Started tailfindr (version 0.1.0) ───────────────────────────────────────────
  ────────────────────────────────────────────────────────────────────────────────
  ☰ You have configured tailfindr as following:
  ❯ fast5_dir:         ./
  ❯ save_dir:          ./
  ❯ csv_filename:      Day1_01_DRS-FAL87078_pass_6dc8999c_347_findr.csv
  ❯ num_cores:         4
  ❯ basecall_group:    Basecall_1D_000
  ❯ save_plots:        FALSE
  ❯ plot_debug_traces: FALSE
  ❯ plotting_library:  rbokeh
  ── Processing started at 2020-04-27 01:31:47 ───────────────────────────────────
  ● Searching for all Fast5 files...
    Done! Found 1 Fast5 files.
  ● Analyzing a single Fast5 file to assess if your data 
    is in an acceptable format...
    ✖ Fatal error! Your data has been basecalled with MinKNOW
      live basecalling which currently does not save the
      Events/Move table in the Analyses/Basecall_1D_000 section of
      the FAST5 file. You should rebasecall your FAST5 files using 
      standalone Guppy or Albacore, and then use tailfindr on the 
      rebasecalled files. Please adjust the value of basecall_group
      parameter in such a case, so that tailfindr can find the 
      Events/Move table in the specified basecall_group. You can
      check which basecall_group the Event/Move is residing by
      opening your FAST5 file in HDFView.
  
      If the Events/Move is present in the data and you have
      specified the correct basecall_group, but you still
      get this error then please open an issue on GitHub:
      https://github.com/adnaniazi/tailfindr/issues
      Remember to attach a few (around 5) of your FAST5 files
      to help us understand the issue.
  ── Processing ended at 2020-04-27 01:32:18 ─────────────────────────────────────
  ✖ tailfindr finished unsuccessfully!
  [1] 0

Work dir:
  /home/callum/master_of_pores/NanoTail/work/ec/9055b7a0d633713ec307041462096f

Tip: you can try to figure out what's wrong by changing to the process work dir and showing the script file named `.command.sh`
Failed to invoke `workflow.onComplete` event handler

 -- Check script 'nanotail.nf' at line: 303 or see '.nextflow.log' file for more details
`

**Comment by adnaniazi** [comment]
Hi Callum,

Please try this command:
find_tails(fast5_dir = './' , save_dir = './', , csv_filename = 'Day1_01_DRS-FAL87078_pass_6dc8999c_347_findr.csv', num_cores = 4, basecall_group = 'Basecall_1D_001')

This command specifies that tailfindr should check for the move table in the Basecall_1D_001 group of the fast5 file. The default is Basecall_1D_000, which in your case would not contain the move table as the data has been live basecalled by MinKNOW. A second round of basecalling should have stored the move table in the Basecall_1D_001 group. I hope this will solve the problem. One additional thing to note is that tailfindr currently does not work with vbz compressed data. So please try tailfindr with uncompressed fast5 file. 

Let me know if this solves your problem.

Adnan

**Comment by callumparr** [comment]
Thank you I will try to see this. 

May I confirm that it should work with gzip, which I think was the standard output compressed fast5 before they introduced VBZ? 

I think I can use hdf5_repack for this. Will get back to you.

**Comment by adnaniazi** [comment]
Yes, it should work with the fast5 compression that was there before VBZ compression was introduced.

**Comment by callumparr** [comment]
Hey so changing the basecall group to 001 worked and output results similar to nanopolish. 

I will now run the h5repack on the fast5 out files from NanoPreprocess.
