### ISSUE TITLE
Lighter version of NanoTail? 

### ISSUE THREAD

**Issue by callumparr** [biocorecrg/master_of_pores#62]
A lighter version of NanoTail which drops tailfindr. It seems it runs much slower than nanopolish. If we have a good reference, the strategy of nanopolish seems more than enough. From the results, they seem very similar. 

Or is there some benefit to running both?

**Comment by enovoa** [comment]
The benefit is that a priori, we didn't know if they would yield similar results or not. So we included both. In some genes they give similar results, but for others they don't.  For the same reason, we include two different softwares in most of our code: two basecallers, two mappers, two gene counters, two polyA tail estimators, two RNA mod prediction methods. Feel free to just nanopolish pA estimation results if you prefer. Thanks!

**Comment by enovoa** [comment]
With regards to making a lighter version of NanoTail, this is something we had considered. However, for the moment it is not a priority. We will update this thread if we do it at some point -thanks!

**Comment by callumparr** [comment]
Agree its not much of a priority. Thank you for the reply and the tools.
