### ISSUE TITLE
Nanopolish only runs with one process/one thread

### ISSUE THREAD

**Issue by callumparr** [biocorecrg/master_of_pores#63]
Nanopolish only uses one thread from what I can see from top 

and 

```
(base) callum@d403:~$ cat /proc/$(pgrep nanopolish)/status | grep -i Threads
Threads:	1

```

If I install manually from git repo and make it runs as expected with the number of threads staed in the command.

**Comment by lucacozzuto** [comment]
Are you referring to nanopolish eventalign in NanoMod?

**Comment by callumparr** [comment]
Ah sorry this is for `nanopolish polya ` in NanoTail , tailfindr spawns multiple R instances as expected but I cannot see this for nanopolish.

**Comment by lucacozzuto** [comment]
It is under control of "big_mem_cpus_time" label in nextflow.config inside the NanoTail folder. If you go inside the folder where nanopolish is run you can have a look at the command line inside the file .command.sh
Here mine:
       nanopolish polya -r multifast.fq.gz  -g reference_sequences.fa -t 8 -b output2_filt.bam

So I specify 8 threads

**Comment by callumparr** [comment]
I set the maximum no. I could for the node I have 

```
#!/bin/bash -ue
#index reads
nanopolish index -d ./ fast5_pass.fq.gz
# polya length estimation
nanopolish polya -r fast5_pass.fq.gz  -g reference_sequences.fa -t 22 -b Day1_04_DRS_NanoPreprocess_filt.bam > Day1_04_DRS_NanoPreprocess-FAL86595_pass_28ffd2c2_89.polya.estimation.tsv
```

This is run with docker because my other option using singularity only has 4 CPUs available.

**Comment by callumparr** [comment]
OK I checked again this morning and it seems to be running the number of processes I expected .
