### ISSUE TITLE
New Tombo Output

### ISSUE THREAD

**Issue by ADelgadoT** [biocorecrg/master_of_pores#64]
Implement new Tombo commands to get an improved output:

**Changes to process getModificationsWitTombo:**

- Modify `tombo detect_modifications` command:
tombo detect_modifications level_sample_compare --fast5-basedirs ${folder_name_A}/* --alternate-fast5-basedirs ${folder_name_B}/* --statistics-file-basename ${folder_name_A}_${folder_name_B}_level_compare_sample --store-p-value

- Delete `tombo text_output signif_sequence_context` command

- Add ` tombo text_output browser_files` command:
tombo text_output browser_files --fast5-basedirs ${folder_name_A}/* --statistics-filename ${folder_name_A}_${folder_name_B}_level_compare_sample.tombo.stats --file-type {coverage,statistic}

Then, it will output the following files per comparison:
- ${folder_name_A}_${folder_name_B}.coverage.sample.(plus|minus).bedgraph
- ${folder_name_A}_${folder_name_B}.coverage.control.(plus|minus).bedgraph
- ${folder_name_A}_${folder_name_B}.statistic.(plus|minus).wig

**Adding new scripts to `NanoMod/bin`:**
- bedgraph2wig.pl
- Merge_Tombo_wigs_MoP.R

**New process to modify Tombo output:** 
- For each bedgraph file from the previous step, run:
`perl bedgraph2wig.pl --bedgraph <infile.bedgraph> --wig <outfile.wig> --step 1 --compact`

- For each group of wig files (coverage.sample + coverage.control + statistic) per strand (plus|minus), run:
Rscript Merge_Tombo_wigs_MoP.R -stats_wig ${folder_name_A}_${folder_name_B}.statistic.(plus|minus).wig -Cov_WT ${folder_name_A}_${folder_name_B}.coverage.sample.(plus|minus).wig -Cov_Control ${folder_name_A}_${folder_name_B}.coverage.control.(plus|minus).wig  -output ${folder_name_A}_${folder_name_B}

It will output a file called: `${folder_name_A}_${folder_name_B}_Tombo_Output.tsv` -> which should be placed in NanoMod's output folder.

**Comment by lucacozzuto** [comment]
Hi @ADelgadoT I miss some outputs. I sent you a DM in slack

**Comment by lucacozzuto** [comment]
Done at https://github.com/biocorecrg/master_of_pores/commit/309b604d577662dc9297eab5b4301970caec3f59
