### ISSUE TITLE
NanoMod fail at beginning 

### ISSUE THREAD

**Issue by callumparr** [biocorecrg/master_of_pores#65]
I am working with some of the data sets used in your frontiers in genetics paper. Two replicates from WT and KO yeast cells. A downsample library for these are output in NanoPreprocess and then I added the output directories into the comparison.tsv. 

I used the transcriptome reference 

`Saccharomyces_cerevisiae.R64-1-1.cdna.all.fa`

I could not find a transcriptome reference for SK1 strain 

I format the comparison.tsv as follows:

multi_fast5_RNAAA023484_WT1 multi_fast5_RNAAA024588_KO1
multi_fast5_RNAAB056712_WT2 multi_fast5_RNAAB058843_KO2

```
(base) callum@d403:~/master_of_pores/NanoMod$ nextflow run nanomod.nf -with-docker
N E X T F L O W  ~  version 20.01.0
Launching `nanomod.nf` [insane_coulomb] - revision: 336d1c0da2
╔╦╗┌─┐┌─┐┌┬┐┌─┐┬─┐  ┌─┐┌─┐  ╔═╗╔═╗╦═╗╔═╗╔═╗
║║║├─┤└─┐ │ ├┤ ├┬┘  │ │├┤   ╠═╝║ ║╠╦╝║╣ ╚═╗
╩ ╩┴ ┴└─┘ ┴ └─┘┴└─  └─┘└    ╩  ╚═╝╩╚═╚═╝╚═╝
                                                                                       
====================================================
BIOCORE@CRG NanoDirectRNA. Detection of modification and polyA length (RNA) - N F  ~  version 0.1
====================================================

*****************   Input files    *******************
input_path                              : /home/callum/master_of_pores/NanoMod/../NanoPreprocess/
comparison                              : /home/callum/master_of_pores/NanoMod/comparison.tsv

********** reference has to be the genome *************
reference                               : /home/callum/master_of_pores/NanoMod/../anno/Saccharomyces_cerevisiae.R64-1-1.cdna.all.fa
output                                  : /home/callum/master_of_pores/NanoMod/Yeast_WT_KO

coverage                                : 5
************* tombo and epinano params ****************
tombo_opt                               : --num-bases 5

epinano_opt                             : 

email                                   :
1

 -- Check script 'nanomod.nf' at line: 87 or see '.nextflow.log' file for more details
1

 -- Check script 'nanomod.nf' at line: 110 or see '.nextflow.log' file for more details
[-        ] process > resquiggling         -
[-        ] process > getModifications     -
[-        ] process > index_reference      -
[-        ] process > call_variants        -
[-        ] process > calc_var_frequencies -
[-        ] process > resquiggling         -
[-        ] process > getModifications     -
[-        ] process > index_reference      -
[-        ] process > call_variants        -
[-        ] process > calc_var_frequencies -
[-        ] process > predict_with_EPInano -
[-        ] process > combineEpinanoPred   -
Skipping the email
```

**Comment by lucacozzuto** [comment]
Please check that comparison.tsv has to be tab-separated and not space separated.  PS: as stated in the help section the reference must be the genome and not the transcriptom.

**Comment by callumparr** [comment]
Thank you. With tabs it is running now.

I was under the impression from tombo documentation and the issue pages, that transcriptome is required for tombo detection with RNA as it cannot deal with splice events. 

Also in the master of pores documentation it says to use a reference transcriptome as input for NanoMod.

I used the cDNA references in NanoPreprocess does that mean I need to repeat the mapping in NanoPreproces with a genome reference to then use NanoMod?

**Comment by lucacozzuto** [comment]
No... Let me double-check maybe this is something old that I have to remove in the help. Thanks for spotting this.

**Comment by callumparr** [comment]
Sorry to clarify transcriptome is expected? I checked Tombo, it is advised to use transcriptome. I also was looking for EpiNano and again transcriptome is expected I believe unless the species as view few splice events in which case genome can be used.
