### ISSUE TITLE
Tailfindr slow

### ISSUE THREAD

**Issue by guillaume-vares** [biocorecrg/master_of_pores#66]
In Nanotail module, Tailfindr is extremely slow in our cluster. It takes several days to compute polyA tails for 2 million transcripts. Is there a way to tweak settings to improve speed? (multithreading, parallel commands). We use Singularity containers, and we are not familiar with configuration.

**Comment by lucacozzuto** [comment]
Tailfindr is below the control of the label  big_mem_cpus in the configuration file nextflow.config within the folder. You can add a queue name that is suitable for your cluster and increase the number of cpus. Have a look if you are really using 8 cpus in your node. PS: the program should already be running in parallel on each multi fast5 subset.
