### ISSUE TITLE
Running Promethion samples

### ISSUE THREAD

**Issue by ADelgadoT** [biocorecrg/master_of_pores#7]
When running PromethION samples (1854 multi fast5), the pipeline stops and returns the error 'No space available on disk'. After some testing, I believe this is due the temporary files in ./work directory. If you delete them, the pipeline can be executed again. 
However, as the temporary files are gone, MOP with --resume flag starts the analysis from the beginning and does not catch any of the previously processed files.

**Comment by lucacozzuto** [comment]
Yes, this is how it works. Temporary data are stored within the work directory. So you might need more disk space for your analysis.
