### ISSUE TITLE
Awk command in basecalling process

### ISSUE THREAD

**Issue by ADelgadoT** [biocorecrg/master_of_pores#72]
Command awk in the basecalling process (Nanopreprocess):
`awk '{if (NR%4==2) gsub(\"U\",\"T\"); print}'`

It fails when it encounters extremely long reads due to memory issues.

**Comment by Huanle** [comment]
what do you mean by extrem long reads?
can you show an example?

**Comment by lucacozzuto** [comment]
Sequences are represented as one line. So when they are Mb long awk fails. We should replace this script with something different.

**Comment by lucacozzuto** [comment]
Fixed in mop2
