### ISSUE TITLE
fastqc not found Nanopreprocess

### ISSUE THREAD

**Issue by samir-watson** [biocorecrg/master_of_pores#74]
Hi,

I am getting the following error when I try run NanoPreprocess:
.command.sh: line 2: fastqc: command not found
![image](https://user-images.githubusercontent.com/63302622/92238132-d7321c00-eeb8-11ea-8959-f1a4dec8e54f.png)

I have fastqc installed in the conda environment Im working with so im not sure what could be the problem.

Thanks

**Comment by lucacozzuto** [comment]
Hi, we don't recommend using master of pores without containers. You can use singularity with -with-singularity

**Comment by samir-watson** [comment]
Hi,
I tried to run it without conda and just using singularity but I keep getting the same error.  It seems there may be an issue with the singularity. I'll keep you updated if I get it to work. Do you have any suggestions on things to try to resolve this?

**Comment by lucacozzuto** [comment]
This is quite strange. Can you verify if the singularity image is there and you can run it?

**Comment by samir-watson** [comment]
Yes, I have two singularity images in the singularity directory
When I run the mopprepr image and call fastqc I get the following output
[cid:image001.png@01D685D0.5BD5AC30]

**Comment by lucacozzuto** [comment]
I cannot see sorry :(

**Comment by lucacozzuto** [comment]
PS: which version of singularity are you using?

**Comment by samir-watson** [comment]
Im using version 3.5.2-1.1.e17

This is the message when I run fastqc in the singularity

(base) [samirwatson@fe1 singularity]$ ls
biocorecrg-mopbasecall-0.1.img  biocorecrg-mopprepr-0.6.img

(base) [samirwatson@fe1 singularity]$ singularity run biocorecrg-mopprepr-0.6.img
Singularity> fastqc
Exception in thread "main" java.awt.HeadlessException:
No X11 DISPLAY variable was set, but this program performed an operation which requires it.
        at java.desktop/java.awt.GraphicsEnvironment.checkHeadless(GraphicsEnvironment.java:208)
        at java.desktop/java.awt.Window.<init>(Window.java:548)
        at java.desktop/java.awt.Frame.<init>(Frame.java:423)
        at java.desktop/java.awt.Frame.<init>(Frame.java:388)
        at java.desktop/javax.swing.JFrame.<init>(JFrame.java:180)
        at uk.ac.babraham.FastQC.FastQCApplication.<init>(FastQCApplication.java:63)
        at uk.ac.babraham.FastQC.FastQCApplication.main(FastQCApplication.java:338)

**Comment by lucacozzuto** [comment]
It looks like is working (you should use fastqc -h or it will try to open a graphical pop up. We however use version 3.2.1 since the newer had some strange behavior.

**Comment by lucacozzuto** [comment]
Hi, can we consider closed this issue?
