### ISSUE TITLE
join_results from NanoTail fails

### ISSUE THREAD

**Issue by NuriaDiaz** [biocorecrg/master_of_pores#78]
Hey!
I am experiencing issues in the last step of the NanoTail. The error I get is the following:

`Error in file(file, "rt") : cannot open the connection
  Calls: read.table -> file
  In addition: Warning message:
  In file(file, "rt") :
    cannot open file 'preprocess_output_wt': No such file or directory
  Execution halted`

As far as I understand, this is an R error. But I do not know how to fix it (I am running into a Linux machine where I did not install R, but the `R --slave -e "library(tailfindr); find_tails(fast5_dir = \'./\' , save_dir = \'./\', ${params.tailfindr_opt}, csv_filename = \'${sampleID}-${fast5_index}_findr.csv\', num_cores = ${task.cpus})"` command from the "process tailfindr" seems to be working (at least gets executed without errors).

'preprocess_output_wt' is the output folder from NanoPreprocess (containing the several output folders automatically generated by the pipeline) that I gave as an input for NanoTail.

Could you please give me a hint on what can be going wrong? or what can I try to fix this error?
Thanks a lot in advance!

Best regards,
Núria

**Comment by lucacozzuto** [comment]
Hi, can you send me the command line you used and the log of the execution?

**Comment by NuriaDiaz** [comment]
Hi,

`nextflow run /home/diaz/master_of_pores/NanoTail/nanotail.nf -with-docker -resume
N E X T F L O W  ~  version 20.07.1
Launching `/home/diaz/master_of_pores/NanoTail/nanotail.nf` [sleepy_picasso] - revision: f311249b93
╔╦╗┌─┐┌─┐┌┬┐┌─┐┬─┐  ┌─┐┌─┐  ╔═╗╔═╗╦═╗╔═╗╔═╗
║║║├─┤└─┐ │ ├┤ ├┬┘  │ │├┤   ╠═╝║ ║╠╦╝║╣ ╚═╗
╩ ╩┴ ┴└─┘ ┴ └─┘┴└─  └─┘└    ╩  ╚═╝╩╚═╚═╝╚═╝
                                                                                       
====================================================
BIOCORE@CRG NanoTail. Detection of polyA length (RNA) - N F  ~  version 0.1
====================================================

*****************   Input files    *********************
input_folders            : /media/data/nuria/nanopore/Fabian/bcn_pipeline/preprocess_output_wt

******* reference has to be the genome **********
reference                : /media/data/nuria/nanopore/isoform-name_gencode.vM25.transcripts.fa
output                   : /media/data/nuria/nanopore/Fabian/bcn_pipeline/nanotail_output_wt

********* nanopolish and tailfindr cmd options **********
nanopolish_opt           :  
tailfindr_opt            : basecall_group='Basecall_1D_001' 

email                     :
executor >  local (1)
[c9/f3e21c] process > check_reference                [100%] 1 of 1, cached: 1 ✔
[6a/ecd49e] process > tailfindr (preprocess_outpu... [100%] 50 of 50, cached:...
[47/1af70d] process > filter_bam (preprocess_outp... [100%] 1 of 1, cached: 1 ✔
[39/7dd76e] process > tail_nanopolish (preprocess... [100%] 50 of 50, cached:...
[74/6fc4e7] process > collect_nanopolish_results ... [100%] 1 of 1, cached: 1 ✔
[a9/7884ca] process > collect_tailfindr_results (... [100%] 1 of 1, cached: 1 ✔
[b8/e5d69b] process > join_results (preprocess_ou... [  0%] 0 of 1
Skipping the email
Error executing process > 'join_results (preprocess_output_wt)'

Caused by:
  Process `join_results (preprocess_output_wt)` terminated with an error exit status (1)

Command executed:

  Rscript --vanilla join.r preprocess_output_wt.findr.len preprocess_output_wt.nanopol.len  preprocess_output_wt

Command exit status:
  1

Command output:
  (empty)
executor >  local (1)
[c9/f3e21c] process > check_reference                [100%] 1 of 1, cached: 1 ✔
[6a/ecd49e] process > tailfindr (preprocess_outpu... [100%] 50 of 50, cached:...
[47/1af70d] process > filter_bam (preprocess_outp... [100%] 1 of 1, cached: 1 ✔
[39/7dd76e] process > tail_nanopolish (preprocess... [100%] 50 of 50, cached:...
[74/6fc4e7] process > collect_nanopolish_results ... [100%] 1 of 1, cached: 1 ✔
[a9/7884ca] process > collect_tailfindr_results (... [100%] 1 of 1, cached: 1 ✔
[b8/e5d69b] process > join_results (preprocess_ou... [100%] 1 of 1, failed: 1 ✘
Skipping the email
Error executing process > 'join_results (preprocess_output_wt)'

Caused by:
  Process `join_results (preprocess_output_wt)` terminated with an error exit status (1)

Command executed:

  Rscript --vanilla join.r preprocess_output_wt.findr.len preprocess_output_wt.nanopol.len  preprocess_output_wt

Command exit status:
  1

Command output:
  (empty)

Command error:
  WARNING: Your kernel does not support swap limit capabilities or the cgroup is not mounted. Memory limited without swap.
  Error in file(file, "rt") : cannot open the connection
  Calls: read.table -> file
  In addition: Warning message:
  In file(file, "rt") :
    cannot open file 'preprocess_output_wt': No such file or directory
  Execution halted

Work dir:
  /media/data/nuria/nanopore/Fabian/bcn_pipeline/preprocess_output_wt/fast5_files/work/b8/e5d69b6724b65c997573ce447d6847

Tip: you can try to figure out what's wrong by changing to the process work dir and showing the script file named `.command.sh`
`
Should I provide something else to help?

Best,
Núria

**Comment by lucacozzuto** [comment]
You can go inside the path /media/data/nuria/nanopore/Fabian/bcn_pipeline/preprocess_output_wt/fast5_files/work/b8/e5d69b6724b65c997573ce447d6847 and have a look at the input files there. Can you check the files and if they are empty?

**Comment by NuriaDiaz** [comment]
In the folder there 2 files and the R script:
join.r
preprocess_output_wt.findr.len
preprocess_output_wt.nanopol.len

both files (findr.len and nanopol.len) have content

Note: every time I press resume the directory giving the issue is a different work one, but the error is the same (just in case this adds up info)

**Comment by lucacozzuto** [comment]
and the content of .command.sh, please :)

**Comment by NuriaDiaz** [comment]
Error in file(file, "rt") : cannot open the connection
Calls: read.table -> file
In addition: Warning message:
In file(file, "rt") :
  cannot open file 'preprocess_output_wt': No such file or directory
Execution halted

**Comment by lucacozzuto** [comment]
No, this is not .command.sh.

**Comment by NuriaDiaz** [comment]
How should I execute .command.sh? isn't it "bash .command.sh"?

**Comment by lucacozzuto** [comment]
cat .command.sh. just to see the content

**Comment by NuriaDiaz** [comment]
#!/bin/bash -ue
Rscript --vanilla join.r preprocess_output_wt.findr.len preprocess_output_wt.nanopol.len  preprocess_output_wt

**Comment by lucacozzuto** [comment]
Ok, did you run the preprocess step turning on the gene count? This is mandatory for Nanomod. I think I have to raise a warning / exception in this case.

**Comment by NuriaDiaz** [comment]
No, I did not turn on gene count during PreProcess because in the "nanopreprocess.nf" file it says that it is optional to perform it (line 502). Is this causing this error I report in NanoTail? -cause you now mention NanoMod and I am not there yet.
Should I use any specific parameters for counting?

**Comment by lucacozzuto** [comment]
Sorry I said NanoMod but I intended NanoTail. It is said in the very first rows of the documentation:
https://github.com/biocorecrg/master_of_pores/blob/master/docs/nanotail.md

**Comment by NuriaDiaz** [comment]
Oh wow, sorry, I completely missed that! If it is so important to run that it might be a good idea to include a warning when executing PreProcess.
Thank you so so much! I will re-run everything and how that I do not run into other errors :)

**Comment by lucacozzuto** [comment]
No problem! Thanks for reporting this, I will keep this open and add a warning :)
