### ISSUE TITLE
Nanopreprocess error

### ISSUE THREAD

**Issue by carlshotwell** [biocorecrg/master_of_pores#79]
Hi below is the error I have been receiving and I can't seem to work my way around it. Any ideas on how I can fix this? 
Thanks! 

Caused by:
  Process `baseCalling (guppy-fast5_pass-3)` terminated with an error exit status (255)

Command executed:

  guppy_basecaller  --flowcell SQK-RNA002 --kit FLO-MIN106 --fast5_out  -i ./ --save_path ./3_out --cpu_threads_per_caller 1  $
  cat 3_out/*.fastq  | awk '{if (NR%4==2) gsub("U","T"); print}'  >> 3.fastq
  rm 3_out/*.fastq
  gzip 3.fastq

Command exit status:
  255

Command output:
  (empty)

Command error:
  WARNING: underlay of /etc/localtime required more than 50 (82) bind mounts
  Could not find matching workflow for flowcell SQK-RNA002 and kit FLO-MIN106

**Comment by lucacozzuto** [comment]
Mmm, this looks like an error of Guppy basecaller. Which version are you using? @ADelgadoT can you help with this?

<<Could not find matching workflow for flowcell SQK-RNA002 and kit FLO-MIN106>>

L

**Comment by enovoa** [comment]
Hi @carlshotwell I would suggest you try to run Guppy outside of MasterOfPores and see if that solves the problem. That will help understand what this error means

**Comment by ADelgadoT** [comment]
Hi, 

It seems that you input  flowcell=SQK-RNA002 and kit=FLO-MIN106. However, input in `params.config` file should be the other way around:
```
flowcell=FLO-MIN106
kit=SQK-RNA002
```

Could you try changing these parameters in the params.config file from NanoPreprocess and resume the execution?

**Comment by lucacozzuto** [comment]
Another question are you using docker or singularity as a container? Can you send me the command line and the log of the program?

**Comment by carlshotwell** [comment]
Thank you for taking a look. I switched the flowcell and kit (dumb mistake on my part I apologize) and that didn't change the error. I believe what the issue is is that I am using a newer version of guppy (which was a module that was already preloaded on my cluster system)and am looking into that as the problem.
