### ISSUE TITLE
deleting temporary files after finishing run

### ISSUE THREAD

**Issue by enovoa** [biocorecrg/master_of_pores#8]
Is there any flag to add to the pipeline to force it to remove the temporary files (instead of doing it manually) once the run is finished and has been completed successfully? Thanks!

**Comment by lucacozzuto** [comment]
As far I know no... but I'll investigate.

**Comment by lucacozzuto** [comment]
It cannot be done since the copy of the final output files is asynchronous... I'm in touch with NextFlow developer to minimise the impact of this.
