### ISSUE TITLE
Debian Med eager to complete Nanopore infrastructure

### ISSUE THREAD

**Issue by smoe** [biocorecrg/master_of_pores#80]
Dear Luca,

Thank you tons for your efforts. Much applauded and appreciated!
On
https://docs.google.com/spreadsheets/d/1tApLhVqxRZ2VOuMH_aPUgFENQJfbLlB_PFH_Ah_q7hM/edit#gid=1806578173
we synchronize the packages that are working on to bring into Debian and its derivatives.

We are not there, yet, but you may find that there is some opportunity to simplify your dockerfiles here and there already. Please feel cordially invited to paste your requests for additional packages that yet escaped our attention.

Cheers,
Steffen

**Comment by lucacozzuto** [comment]
Thanks! We have a plan to simplify / remove some of the docker containers in future.
