### ISSUE TITLE
Questions regarding to proper use

### ISSUE THREAD

**Issue by vgori** [biocorecrg/master_of_pores#84]
Dear authors,
we would really appreciate your suggestions on the following points on how to properly use the "master_of_pores" pipeline.

We have installed the Master of Pores, and performed the nanopreprocess step, and now we are quite puzzled how to correctly configure NanoMod, which uses Tombo and Epinano to identify the potential RNA-Modifications between two samples. In our case, exposed to radiation (experimental) and non-exposed (control).

We would be more than happy if you answer on the questions below:

  1. What files from Nanopreprocess output does NanoMod take as input? Are they fasta5 and alignment files?
  2. What should exactly the file comparison.tsv contain? Is that path to files (or folders name) from control /experiment input or just sample IDs? It is not obvious from example https://github.com/biocorecrg/master_of_pores/blob/master/NanoMod/comparison.tsv
  3. What is the modification identification method implicated within the Master of Pores? Is that model_sample_compare? Can it be changed to level_sample_compare or de_novo?
  4. Please let us know how the following options of NanoMod algorithm should be set: coverage, tombo_opt, epinano_opt?

Best regards,
Veronica

**Comment by enovoa** [comment]
Hi @vgori 

Thanks for your interest in MoP. With regards to your specific questions:

1. Please take a look at the NanoMod MasterOfPores documentation: https://biocorecrg.github.io/master_of_pores/nanomod.html, all details of inputs and outputs are explained there. The inputs are the folders.
2. The comparison.tsv is the folder names that are used as input. The path is defined in a separate variable. 
3. NanoMod runs Tombo and EpiNano. You can change how tombo is run by changing the code in the NanoMod nextflow file. You can fork the repo and do the edits that you might find more convenient for your samples. 
4. We cannot provide specific recommendations for your samples, as it may vary from species to species, RNA mod type, RNA molecule type, etc. We provide some defaults that have worked well for our specific test cases, but you might need to tweak the parameters for your specific cases.

Best,
Eva
