### ISSUE TITLE
Problems in starting the NanoPreprocess

### ISSUE THREAD

**Issue by hqs10** [biocorecrg/master_of_pores#87]
Hi all,

Please let me know your thoughts on fixing the following error, which I got after attempting to start NanoPreprocessing:

[21/41cfba] process > testInput (MasterIn_fast5) [  0%] 0 of 1
[-        ] process > baseCalling                -
[-        ] process > concatenateFastQFiles      -
[-        ] process > QC                         -
[-        ] process > fastQC                     -
[-        ] process > mapping                    -
[-        ] process > alnQC                      -
[-        ] process > joinAlnQCs                 -
[-        ] process > alnQC2                     -
[-        ] process > multiQC                    -
Skipping the email
executor >  local (1)
[21/41cfba] process > testInput (MasterIn_fast5) [100%] 1 of 1, failed: 1 ✘
[-        ] process > baseCalling                -
[-        ] process > concatenateFastQFiles      -
[-        ] process > QC                         -
[-        ] process > fastQC                     -
[-        ] process > mapping                    -
[-        ] process > alnQC                      -
[-        ] process > joinAlnQCs                 -
[-        ] process > alnQC2                     -
[-        ] process > multiQC                    -
Skipping the email
Error executing process > 'testInput (MasterIn_fast5)'

Caused by:
  Process `testInput (MasterIn_fast5)` terminated with an error exit status (1)

Command executed:

  fast5_type.py MasterIn_fast5

Command exit status:
  1

Command output:
  (empty)

Command error:
  /usr/local/python/versions/3.6.3/lib/python3.6/site-packages/h5py/__init__.py:36: FutureWarning: Conversion of the second argument of issubdtype from `float` to `np.floating` is deprecated. In future, it will be treated as `np.float64 == np.dtype(float).type`.
    from ._conv import register_converters as _register_converters
  Traceback (most recent call last):
    File "/media/localarchive/master_of_pores/NanoPreprocess/bin/fast5_type.py", line 22, in <module>
      hdf5 = h5py.File(f5file,'r')
    File "/usr/local/python/versions/3.6.3/lib/python3.6/site-packages/h5py/_hl/files.py", line 269, in __init__
      fid = make_fid(name, mode, userblock_size, fapl, swmr=swmr)
    File "/usr/local/python/versions/3.6.3/lib/python3.6/site-packages/h5py/_hl/files.py", line 99, in make_fid
      fid = h5f.open(name, flags, fapl=fapl)
    File "h5py/_objects.pyx", line 54, in h5py._objects.with_phil.wrapper
    File "h5py/_objects.pyx", line 55, in h5py._objects.with_phil.wrapper
    File "h5py/h5f.pyx", line 78, in h5py.h5f.open
  OSError: Unable to open file (file read failed: time = Tue Nov 17 09:59:20 2020
  , filename = 'MasterIn_fast5', file descriptor = 3, errno = 21, error message = 'Is a directory', buf = 0x7ffd78a6d1d0, total read size = 8, bytes this sub-read = 8, bytes actually read = 18446744073709551615, offset = 0)

Work dir:
  /media/localarchive/master_of_pores/NanoPreprocess/work/21/41cfbabfb2fc5ff7d54c2e83a93083

**Comment by lucacozzuto** [comment]
Dear @hqs10, can you send me your command line, please?

**Comment by hqs10** [comment]
> Dear @hqs10, can you send me your command line, please?

Thanks for the fast reply, Luca.

Please see below:

/media/localarchive/master_of_pores/NanoPreprocess# nextflow run nanopreprocess.nf -with-docker
N E X T F L O W  ~  version 20.07.1
Launching `nanopreprocess.nf` [romantic_nightingale] - revision: 9b1fb78da4
╔╦╗┌─┐┌─┐┌┬┐┌─┐┬─┐  ┌─┐┌─┐  ╔═╗╔═╗╦═╗╔═╗╔═╗
║║║├─┤└─┐ │ ├┤ ├┬┘  │ │├┤   ╠═╝║ ║╠╦╝║╣ ╚═╗
╩ ╩┴ ┴└─┘ ┴ └─┘┴└─  └─┘└    ╩  ╚═╝╩╚═╚═╝╚═╝

====================================================
BIOCORE@CRG Preprocessing of Nanopore direct RNA - N F  ~  version 0.1
====================================================

kit                       : SQK-RNA002
flowcell                  : FLO-MIN106D
fast5                     : /media/localarchive/MasterIn_fast5
reference                 : /media/localarchive/DataRRP/Homo_sapiens.GRCh38.cdna.all.fa
annotation                : /media/localarchive/DataRRP/Homo_sapiens.GRCh38.93.gtf

ref_type                  : transcriptome
seq_type                  : RNA

output                    : /media/localarchive/MasterOut
qualityqc                 : 5
granularity               :

basecaller                : program.albacore
basecaller_opt            :
GPU                       : OFF
demultiplexing            :
demultiplexing_opt        : -m pAmps-final-actrun_newdata_nanopore_UResNet20v2_model.030.h5

filter                    : OFF
filter_opt                :
mapper                    : minimap2
mapper_opt                : -uf -k14
map_type                  : unspliced

counter                   : NO
counter_opt               :

email                     :

**Comment by lucacozzuto** [comment]
Ok, so you are indicating a folder as fast5 input. You should indicate fast5 files. See the example here:
```
    fast5               = "$baseDir/../data/multifast/*.fast5"
```

https://github.com/biocorecrg/master_of_pores/blob/master/NanoPreprocess/params.config

Moreover the basecaller parameter can be either guppy or albacore. You indicate "program.albacore" that is not recognized.

**Comment by hqs10** [comment]
> Ok, so you are indicating a folder as fast5 input. You should indicate fast5 files. See the example here:
> 
> ```
>     fast5               = "$baseDir/../data/multifast/*.fast5"
> ```
> 
> https://github.com/biocorecrg/master_of_pores/blob/master/NanoPreprocess/params.config
> 
> Moreover the basecaller parameter can be either guppy or albacore. You indicate "program.albacore" that is not recognized.

Thanks, Luca. 

After editing the params.config accordingly it fixed the previous error
But I faced a new one regarding the base-calling process. However, I have installed the albacore executive file inside the bin directory of NanoPreProcess. Please see the error below:

N E X T F L O W  ~  version 20.07.1
Launching `nanopreprocess.nf` [gigantic_heisenberg] - revision: 9b1fb78da4
╔╦╗┌─┐┌─┐┌┬┐┌─┐┬─┐  ┌─┐┌─┐  ╔═╗╔═╗╦═╗╔═╗╔═╗
║║║├─┤└─┐ │ ├┤ ├┬┘  │ │├┤   ╠═╝║ ║╠╦╝║╣ ╚═╗
╩ ╩┴ ┴└─┘ ┴ └─┘┴└─  └─┘└    ╩  ╚═╝╩╚═╚═╝╚═╝

====================================================
BIOCORE@CRG Preprocessing of Nanopore direct RNA - N F  ~  version 0.1
====================================================

kit                       : SQK-RNA002
flowcell                  : FLO-MIN106D
fast5                     : /media/localarchive/MasterIn_fast5/*.fast5
reference                 : /media/localarchive/DataRRP/Homo_sapiens.GRCh38.cdna.all.fa
annotation                : /media/localarchive/DataRRP/Homo_sapiens.GRCh38.93.gtf

ref_type                  : transcriptome
seq_type                  : RNA

output                    : /media/localarchive/MasterOut
qualityqc                 : 5
granularity               :

basecaller                : albacore
basecaller_opt            :
GPU                       : OFF
demultiplexing            :
demultiplexing_opt        : -m pAmps-final-actrun_newdata_nanopore_UResNet20v2_model.030.h5

filter                    : OFF
filter_opt                :
mapper                    : minimap2
mapper_opt                : -uf -k14
map_type                  : unspliced

counter                   : NO
counter_opt               :

email                     :
executor >  local (3)
[90/d71299] process > testInput (all_reads.fast5)             [100%] 1 of 1 ✔
[41/bd37ce] process > baseCalling (albacore-MasterIn_fast5-1) [  0%] 0 of 2
[-        ] process > concatenateFastQFiles                   -
[-        ] process > QC                                      -
[-        ] process > fastQC                                  -
[-        ] process > mapping                                 -
[-        ] process > alnQC                                   -
[-        ] process > joinAlnQCs                              -
[-        ] process > alnQC2                                  -
[-        ] process > multiQC                                 -
Skipping the email
MultiFast5 files detected!
Error executing process > 'baseCalling (albacore-MasterIn_fast5-1)'

executor >  local (3)
[90/d71299] process > testInput (all_reads.fast5)             [100%] 1 of 1 ✔
[8d/7f2e0b] process > baseCalling (albacore-MasterIn_fast5-0) [100%] 1 of 1, failed: 1
[-        ] process > concatenateFastQFiles                   -
[-        ] process > QC                                      -
[-        ] process > fastQC                                  -
[-        ] process > mapping                                 -
[-        ] process > alnQC                                   -
[-        ] process > joinAlnQCs                              -
[-        ] process > alnQC2                                  -
[-        ] process > multiQC                                 -
Skipping the email
MultiFast5 files detected!
Error executing process > 'baseCalling (albacore-MasterIn_fast5-1)'

Caused by:
  Process `baseCalling (albacore-MasterIn_fast5-1)` terminated with an error exit status (127)

Command executed:

  mkdir demulti_tmp; mkdir demulti; multi_to_single_fast5 -i ./ -s demulti_tmp -t 8; mv demulti_tmp/*/*.fast5 demulti; rm -fr demulti_tmp
      export PYTHONPATH=/media/localarchive/master_of_pores/NanoPreprocess/bin/albacore:$PYTHONPATH
  read_fast5_basecaller.py  --flowcell "FLO-MIN106D" --kit "SQK-RNA002" --output_format fastq,fast5                     --worker_threads 8 -s ./1_out --disable_filtering --input demulti;
  cat 1_out/workspace/*.fastq  | awk '{if (NR%4==2) gsub("U","T"); print}'  >> 1.fastq
  rm 1_out/workspace/*.fastq
  gzip 1.fastq
  mkdir single_basecallings
  mv 1_out/workspace/*/*.fast5 single_basecallings
  mkdir temp_multi
        single_to_multi_fast5 -i single_basecallings -s temp_multi -t 8
        mv temp_multi/batch_0.fast5 ./1_out/workspace/batch_1.fast5
  if [-d demulti]; then rm -fr demulti; fi
  rm -fr single_basecallings temp_multi

Command exit status:
  127

Command output:
  (empty)

Command error:
  | 0 of 1|                                                  |  0% ETA:  --:--:--
  / 1 of 1|###################################################|100% ETA:  0:00:00
  | 1 of 1|###################################################|100% Time: 0:00:06
  .command.sh: line 4: read_fast5_basecaller.py: command not found

Work dir:
  /media/localarchive/master_of_pores/NanoPreprocess/work/41/bd37ceca99199ab90defb643f0bb19

Tip: view the complete command output by changing to the process work dir and entering the command `cat .command.out`

**Comment by lucacozzuto** [comment]
Dear @hqs10, have you followed all the instructions here?
https://github.com/biocorecrg/master_of_pores/blob/master/docs/install.md#b-albacore

please let me know if it works or not

**Comment by hqs10** [comment]
> Dear @hqs10, have you followed all the instructions here?
> https://github.com/biocorecrg/master_of_pores/blob/master/docs/install.md#b-albacore
> 
> please let me know if it works or not

Dear @lucacozzuto 

I have followed several times the installation guide of MoP, and tried different versions of Guppy (3.1.5, and 4.2.2). We have compatible 2x of GPU RTX 2080 ti and successfully installed CUDA drivers. And each time I got an error. 

Please see below the error report of my recent attempt to run nanopreprocess using Guppy 3.1.5.

(base) root@phe-a280025x9812321:~/master_of_pores/NanoPreprocess# nextflow run nanopreprocess.nf -with-docker
N E X T F L O W  ~  version 20.07.1
Launching `nanopreprocess.nf` [lethal_einstein] - revision: 9b1fb78da4
╔╦╗┌─┐┌─┐┌┬┐┌─┐┬─┐  ┌─┐┌─┐  ╔═╗╔═╗╦═╗╔═╗╔═╗
║║║├─┤└─┐ │ ├┤ ├┬┘  │ │├┤   ╠═╝║ ║╠╦╝║╣ ╚═╗
╩ ╩┴ ┴└─┘ ┴ └─┘┴└─  └─┘└    ╩  ╚═╝╩╚═╚═╝╚═╝

====================================================
BIOCORE@CRG Preprocessing of Nanopore direct RNA - N F  ~  version 0.1
====================================================

kit                       : SQK-RNA002
flowcell                  : FLO-MIN106D
fast5                     : /media/localarchive/MasterIn_fast5/*.fast5
reference                 : /media/localarchive/DataRRP/Homo_sapiens.GRCh38.cdna.all.fa
annotation                : /media/localarchive/DataRRP/Homo_sapiens.GRCh38.93.gtf

ref_type                  : transcriptome
seq_type                  : RNA

output                    : /media/localarchive/MasterOut
qualityqc                 : 5
granularity               :

basecaller                : guppy
basecaller_opt            :
GPU                       : OFF
demultiplexing            :
demultiplexing_opt        : -m pAmps-final-actrun_newdata_nanopore_UResNet20v2_model.030.h5

filter                    : OFF
filter_opt                :
mapper                    : minimap2
mapper_opt                : -uf -k14
map_type                  : unspliced

counter                   : NO
counter_opt               :

email                     :
executor >  local (3)
[06/73991b] process > testInput (all_reads.fast5)          [100%] 1 of 1 ✔
[8c/d71ae6] process > baseCalling (guppy-MasterIn_fast5-1) [  0%] 0 of 2
[-        ] process > concatenateFastQFiles                -
[-        ] process > QC                                   -
[-        ] process > fastQC                               -
executor >  local (3)
[06/73991b] process > testInput (all_reads.fast5)          [100%] 1 of 1 ✔
[22/642ab0] process > baseCalling (guppy-MasterIn_fast5-0) [100%] 1 of 1, failed: 1
[-        ] process > concatenateFastQFiles                -
[-        ] process > QC                                   -
[-        ] process > fastQC                               -
[-        ] process > mapping                              -
[-        ] process > alnQC                                -
[-        ] process > joinAlnQCs                           -
[-        ] process > alnQC2                               -
[-        ] process > multiQC                              -
Skipping the email
MultiFast5 files detected!
Error executing process > 'baseCalling (guppy-MasterIn_fast5-1)'

Caused by:
  Process `baseCalling (guppy-MasterIn_fast5-1)` terminated with an error exit status (127)

Command executed:

  guppy_basecaller  --flowcell FLO-MIN106D --kit SQK-RNA002 --fast5_out  -i ./ --save_path ./1_out --cpu_threads_per_caller 1  --num_callers  8
  cat 1_out/*.fastq  | awk '{if (NR%4==2) gsub("U","T"); print}'  >> 1.fastq
  rm 1_out/*.fastq
  gzip 1.fastq

Command exit status:
  127

Command output:
  (empty)

Command error:
  .command.sh: line 2: guppy_basecaller: command not found

Work dir:
  /home/phe.gov.uk/stanislav.polozov/master_of_pores/NanoPreprocess/work/8c/d71ae680086e06da8f435761c6f9fe

Tip: when you have fixed the problem you can continue the execution adding the option `-resume` to the run command line

**Comment by lucacozzuto** [comment]
Hi,
the error I see is  ```.command.sh: line 2: guppy_basecaller: command not found```.
Can you show me the content of your NanoPreprocess/bin/ folder, please?

**Comment by hqs10** [comment]
Dear @lucacozzuto 

Sure. Please see the screenshot of ../bin/ directory below:

![image](https://user-images.githubusercontent.com/60135958/99387913-aa44b100-28cc-11eb-84c8-30935d8622d8.png)

**Comment by lucacozzuto** [comment]
I see that the command ```ln -s ont-guppy_3.1.5_linux64/ont-guppy/bin/guppy_* .```  is giving you a broken link, because the folder where you have guppy is named ont-guppy. Can you do the link in this way?

```ln -s ont-guppy/ont-guppy/bin/guppy_* .``` or change the name of the folder accordingly.

**Comment by hqs10** [comment]
> I see that the command `ln -s ont-guppy_3.1.5_linux64/ont-guppy/bin/guppy_* .` is giving you a broken link, because the folder where you have guppy is named ont-guppy. Can you do the link in this way?
> 
> `ln -s ont-guppy/ont-guppy/bin/guppy_* .` or change the name of the folder accordingly.

Dear @lucacozzuto,

Unfortunately, it yielded no result. 

I have renamed the directory "ont-guppy" to "ont-guppy_3.1.5_linux64", and then executed `ln -s ont-guppy_3.1.5_linux64/ont-guppy/bin/guppy_* .`

Afterwards, I started nanopreprocess and got the error as before.

**Comment by lucacozzuto** [comment]
I got it. I think you should create a folder named guppy_3.1.5_linux64 and move the ont-guppy inside it. Inside you should have a bin folder and these files:
- guppy_aligner
- guppy_barcoder
- guppy_basecaller
L

**Comment by hqs10** [comment]
> I got it. I think you should create a folder named guppy_3.1.5_linux64 and move the ont-guppy inside it. Inside you should have a bin folder and these files:
> 
> * guppy_aligner
> * guppy_barcoder
> * guppy_basecaller
>   L

Dear @lucacozzuto ,

It seems that your recommendations helped me to fix the error `.command.sh: line 2: guppy_basecaller: command not found.`

However, I faced new error  `Could not find matching workflow for flowcell FLO-MIN106D and kit SQK-RNA002`

Please see below more detailed:



(base) root@phe-a280025x9812321:~/master_of_pores/NanoPreprocess# nextflow run nanopreprocess.nf -with-docker
N E X T F L O W  ~  version 20.07.1
Launching `nanopreprocess.nf` [sick_joliot] - revision: 9b1fb78da4
╔╦╗┌─┐┌─┐┌┬┐┌─┐┬─┐  ┌─┐┌─┐  ╔═╗╔═╗╦═╗╔═╗╔═╗
║║║├─┤└─┐ │ ├┤ ├┬┘  │ │├┤   ╠═╝║ ║╠╦╝║╣ ╚═╗
╩ ╩┴ ┴└─┘ ┴ └─┘┴└─  └─┘└    ╩  ╚═╝╩╚═╚═╝╚═╝

====================================================
BIOCORE@CRG Preprocessing of Nanopore direct RNA - N F  ~  version 0.1
====================================================

kit                       : SQK-RNA002
flowcell                  : FLO-MIN106D
fast5                     : /media/localarchive/MasterIn_fast5/*.fast5
reference                 : /media/localarchive/DataRRP/Homo_sapiens.GRCh38.cdna.all.fa
annotation                : /media/localarchive/DataRRP/Homo_sapiens.GRCh38.93.gtf

ref_type                  : transcriptome
seq_type                  : RNA

output                    : /media/localarchive/MasterOut
qualityqc                 : 5
granularity               :

basecaller                : guppy
basecaller_opt            :
GPU                       : OFF
demultiplexing            :
demultiplexing_opt        : -m pAmps-final-actrun_newdata_nanopore_UResNet20v2_model.030.h5

filter                    : OFF
filter_opt                :
mapper                    : minimap2
mapper_opt                : -uf -k14
map_type                  : unspliced

counter                   : NO
counter_opt               :

email                     :
executor >  local (3)
[44/78ea1c] process > testInput (all_reads.fast5)          [100%] 1 of 1 ✔
[ed/6aa8c2] process > baseCalling (guppy-MasterIn_fast5-1) [  0%] 0 of 2
[-        ] process > concatenateFastQFiles                -
[-        ] process > QC                                   -
[-        ] process > fastQC                               -
executor >  local (3)
[44/78ea1c] process > testInput (all_reads.fast5)          [100%] 1 of 1 ✔
[ed/6aa8c2] process > baseCalling (guppy-MasterIn_fast5-1) [100%] 1 of 1, failed: 1
[-        ] process > concatenateFastQFiles                -
[-        ] process > QC                                   -
[-        ] process > fastQC                               -
[-        ] process > mapping                              -
[-        ] process > alnQC                                -
[-        ] process > joinAlnQCs                           -
[-        ] process > alnQC2                               -
[-        ] process > multiQC                              -
Skipping the email
MultiFast5 files detected!
Error executing process > 'baseCalling (guppy-MasterIn_fast5-0)'

Caused by:
  Process `baseCalling (guppy-MasterIn_fast5-0)` terminated with an error exit status (255)

Command executed:

  guppy_basecaller  --flowcell FLO-MIN106D --kit SQK-RNA002 --fast5_out  -i ./ --save_path ./0_out --cpu_threads_per_caller 1  --num_callers  8
  cat 0_out/*.fastq  | awk '{if (NR%4==2) gsub("U","T"); print}'  >> 0.fastq
  rm 0_out/*.fastq
  gzip 0.fastq

Command exit status:
  255

Command output:
  (empty)

Command error:
  Could not find matching workflow for flowcell FLO-MIN106D and kit SQK-RNA002

Work dir:
  /home/phe.gov.uk/stanislav.polozov/master_of_pores/NanoPreprocess/work/74/33d48624369d0de527231e8511fd21

Tip: when you have fixed the problem you can continue the execution adding the option `-resume` to the run command line

**Comment by lucacozzuto** [comment]
This looks like this problem:
https://github.com/biocorecrg/master_of_pores/issues/79
You should change the parameters according to the version of guppy you are using and the kind of sequencing you are doing.

**Comment by hqs10** [comment]
> This looks like this problem:
> #79
> You should change the parameters according to the version of guppy you are using and the kind of sequencing you are doing.

Dear @lucacozzuto ,

Thank you very much for your help today. It seems that guppy did not recognise the "FLO-MIN106D" input parameter. I have put FLO-MIN106 instead, and it seems to be working!

**Comment by lucacozzuto** [comment]
Good! Let me know if everything goes well!
Best,

L

**Comment by manburst** [comment]
Hello sir
I got a similar issue but in my case, it said that

```
Single Fast5 files detected!
Error executing process > 'baseCalling (albacore-jirachote-0)'

Caused by:
  Process `baseCalling (albacore-jirachote-0)` terminated with an error exit status (1)

Command executed:

  export PYTHONPATH=/home/jirachote/master_of_pores/NanoPreprocess/bin/albacore:$PYTHONPATH
  read_fast5_basecaller.py  --flowcell "FLO-MIN106" --kit "SQK-RNA001" --output_format fastq,fast5 			--worker_threads 2 -s ./0_out --disable_filtering --input ./;
  cat 0_out/workspace/*.fastq  >> 0.fastq
  rm 0_out/workspace/*.fastq
  gzip 0.fastq
  mkdir single_basecallings
  mv 0_out/workspace/*/*.fast5 single_basecallings
  mkdir temp_multi
        single_to_multi_fast5 -i single_basecallings -s temp_multi -t 2
        mv temp_multi/batch_0.fast5 ./0_out/workspace/batch_0.fast5
  if [-d demulti]; then rm -fr demulti; fi
  rm -fr single_basecallings temp_multi

Command exit status:
  1

Command output:
  (empty)

Command error:
  .command.sh: line 2: PYTHONPATH: unbound variable

Work dir:
  /home/jirachote/master_of_pores/NanoPreprocess/work/c4/ce1aeccda06f4625cf93b64704161e

Tip: view the complete command output by changing to the process work dir and entering the command `cat .command.out`
```
I have already followed the step 
```
cd master_of_pores/NanoPreprocess/bin
pip3 install --target=./albacore ont_albacore-2.1.7-cp36-cp36m-manylinux1_x86_64.whl
$ ln -s albacore/bin/multi_to_single_fast5 
$ ln -s albacore/bin/read_fast5_basecaller.py .
```
Here is my screenshot in bin folder
![image](https://user-images.githubusercontent.com/68594551/106978467-ea5e5600-678e-11eb-9a09-ae2fd3ebb4bf.png)
The error is caused by python path but how to solve this?

**Comment by manburst** [comment]
I think my python version is not 3.6 but somehow I couldn't change python on my ubuntu. Now it can run with guppy
but I got a new problem about the QC process
```
executor >  local (11)
[76/46c0fb] process > testInput (test.fast5)            [100%] 1 of 1 ✔
[98/9e0f54] process > baseCalling (guppy-jirachote-0)   [100%] 1 of 1 ✔
[6d/20db92] process > filtering (nanofilt-0)            [100%] 1 of 1 ✔
[97/9c5434] process > concatenateFastQFiles (jirachote) [100%] 1 of 1 ✔
[31/6381a1] process > QC (jirachote)                    [100%] 1 of 1, failed: 1 ✔
[0c/fd7180] process > fastQC (jirachote)                [100%] 1 of 1 ✔
[59/542102] process > mapping (minimap2-jirachote)      [100%] 1 of 1 ✔
[e1/0803dd] process > alnQC (jirachote)                 [100%] 1 of 1 ✔
[e6/e4ec32] process > joinAlnQCs                        [100%] 1 of 1 ✔
[44/887dfa] process > alnQC2 (jirachote)                [100%] 1 of 1, failed: 1 ✔
[64/d1319d] process > multiQC                           [100%] 1 of 1, failed: 1 ✘
Skipping the email
Single Fast5 files detected!
Error executing process > 'multiQC'

Caused by:
  Process `multiQC` terminated with an error exit status (127)

Command executed:

  multiqc -c config.yaml .

Command exit status:
  127

Command output:
  (empty)

Command error:
  .command.sh: line 2: multiqc: command not found
```

**Comment by lucacozzuto** [comment]
Hi, you should use either docker or singularity container. Apparently you are running without -with-singularity or -with-docker parameter.
