### ISSUE TITLE
NanoMod issues: Stops at index_reference 

### ISSUE THREAD

**Issue by hqs10** [biocorecrg/master_of_pores#88]
Dear all, 
Dear @lucacozzuto ,

I would really appreciate your assistance in solving the following issue, which occurred when I tried to run NanoMod. 

Please see the issue below. 

(base) root@........:/media/localarchive/master_of_pores/NanoMod# nextflow run nanomod.nf -with-docker
N E X T F L O W  ~  version 20.07.1
Launching `nanomod.nf` [modest_carlsson] - revision: ae4d8a4c65
╔╦╗┌─┐┌─┐┌┬┐┌─┐┬─┐  ┌─┐┌─┐  ╔═╗╔═╗╦═╗╔═╗╔═╗
║║║├─┤└─┐ │ ├┤ ├┬┘  │ │├┤   ╠═╝║ ║╠╦╝║╣ ╚═╗
╩ ╩┴ ┴└─┘ ┴ └─┘┴└─  └─┘└    ╩  ╚═╝╩╚═╚═╝╚═╝

====================================================
BIOCORE@CRG NanoDirectRNA. Detection of modification and polyA length (RNA) - N F  ~  version 0.1
====================================================

*****************   Input files    *******************
input_path                              : /media/localarchive/MasterOut
comparison                              : /media/localarchive/master_of_pores/NanoMod/comparison.tsv

********** reference has to be the genome *************
reference                               : /media/localarchive/DataRRP/Homo_sapiens.GRCh38.cdna.all.fa
output                                  : /media/localarchive/NanoMod_output

coverage                                : 5
************* tombo and epinano params ****************
tombo_opt                               : --num-bases 5

epinano_opt                             :

email                                   :
executor >  local (1)
[-        ] process > resquiggling                 -
[-        ] process > getModifications             -
[7c/08274e] process > index_reference              [  0%] 0 of 1
[-        ] process > CallVariantsForEpinano       -
executor >  local (1)
[-        ] process > resquiggling                 -
[-        ] process > getModifications             -
[7c/08274e] process > index_reference              [100%] 1 of 1 ✔
[-        ] process > CallVariantsForEpinano       -
[-        ] process > calcVarFrequenciesForEpinano -
Skipping the email

**Comment by lucacozzuto** [comment]
Hi, can you show me the content of comparison.tsv and the content of the folder /media/localarchive/MasterOut, please?

**Comment by hqs10** [comment]
> Hi, can you show me the content of comparison.tsv and the content of the folder /media/localarchive/MasterOut, please?

@lucacozzuto, Thanks for the fast reply!
Sure.

Please see below the content of comparison.tsv:
![image](https://user-images.githubusercontent.com/60135958/99433394-5dc99780-2905-11eb-958f-6d54b0a5d668.png)

Please see below the content of MasterOut:
![image](https://user-images.githubusercontent.com/60135958/99433503-7f2a8380-2905-11eb-86e1-4bd985197f4f.png)

**Comment by lucacozzuto** [comment]
Ok so please have a look at the documentation here:
https://biocorecrg.github.io/master_of_pores/nanomod.html
In brief you need to run nanoPreprocess on the two datasets and generate two different outputs (i.e. two folders) and then you can use nanomod to make comparison between them.

L

**Comment by hqs10** [comment]
> Ok so please have a look at the documentation here:
> https://biocorecrg.github.io/master_of_pores/nanomod.html
> In brief you need to run nanoPreprocess on the two datasets and generate two different outputs (i.e. two folders) and then you can use nanomod to make comparison between them.
> 
> L

Thanks for sharing that. I have read the documentation https://biocorecrg.github.io/master_of_pores/nanomod.html
and it was clear that we need to work with two data sets (i.e. to compare control/exp). 

Just to clarify the main steps:
1) I run nanopreprocess for .fasta5 files from experimental and control samples (e.g. WT and KO) separately from each other (step-by-step). As result, two or more different **nanopreprocess output** folders are formed.
2) Afterwards, I place these two or more **nanopreprocess output folders** into the **common folder**, which is intended for the input to Nanomod.
3) I edit comparison.tsv respectively to the names of **nanopreprocess output folders**, which correspond to the experimental or control sample.
4) I run Nanomod

Please let me know is it correct?

Best regards,

Stan

**Comment by lucacozzuto** [comment]
Yes it is fine

L

Il mar 17 nov 2020, 20:17 Stan <notifications@github.com> ha scritto:

**Comment by hqs10** [comment]
Dear @lucacozzuto , everything worked perfectly. Thank you so much for your advice.

**Comment by lucacozzuto** [comment]
You are welcome!
