### ISSUE TITLE
#QUESTION: to detect m6A RNA modifications 

### ISSUE THREAD

**Issue by hqs10** [biocorecrg/master_of_pores#89]
Dear all, Dear @lucacozzuto,

I am happy to inform that sample comparison Tombo model worked perfectly on our data set.

However, we also need to use `tombo detect_modifications alternative_model` with the `--alternate-bases 5mC 6mA` option. 
Please let me know, do you have any "nanomod.nf" available, which is set on these model and params? 

How can we limit nonamod to search for modifications among specific motifs (e.g. DRACH motifs)? 

Really appreciate any reply. 

Stan

**Comment by ADelgadoT** [comment]
Hi Stan, 

Currently NanoMod can not be limited to specific kmers. However, if you want to add these modifications, you can submit a pull request and we'd be happy to incorporate these changes. 

Thank you, 

Anna

**Comment by hqs10** [comment]
> Hi Stan, 
> 
> 
> 
> Currently NanoMod can not be limited to specific kmers. However, if you want to add these modifications, you can submit a pull request and we'd be happy to incorporate these changes. 
> 
> 
> 
> Thank you, 
> 
> 
> 
> Anna

Thanks for the reply, Anna!

Sure. If we are successful in modifying NanoMod to search for specific kmers, we would be happy to submit the pull-request. 

Please let me also know, did you try the following tombo method 
`tombo detect_modifications alternative_model` with the `--alternate-bases 5mC 6mA`? 

Best regards,

Stan

**Comment by ADelgadoT** [comment]
Hi Stan, 

Sorry for the late reply. We have not used the` tombo detect_modifications alternative_model` with the `--alternate-bases 5mC 6mA` inside MoP. However, NanoMod could be modified to run Tombo in this mode. If you are successful, we would be happy to submit the pull-request. 

Thanks! 

Anna
