### ISSUE TITLE
add demultiplexing option for cDNA libraries

### ISSUE THREAD

**Issue by enovoa** [biocorecrg/master_of_pores#9]
https://github.com/rrwick/Porechop 

We should allow the user to decide if adapters are in one side or in both (depending on how library is prepared, sometime adapter is only in one end

**Comment by lucacozzuto** [comment]
@Huanle @enovoa @lpryszcz I would need some examples for introducing the step of demultiplexing (at least for gDNA). Can you send it to me, please?

**Comment by lpryszcz** [comment]
Hi @lucacozzuto , you can find the commands with some more examples and some parameters explained in details in the [doc](https://docs.google.com/document/d/1fU544ChS7yaZvMtQMo23djOW4Ux-RNIqxptTjbiszQI/edit#heading=h.o2qeaj66jkho). In brief: 
```
guppy_basecaller --device cuda:0 -c dna_r9.4.1_450bps_hac.cfg --compress_fastq -ri $d -s /hdd/basecalling/guppy3/$n --barcode_kits EXP-NBD104 --trim_barcodes --require_barcodes_both_ends
```

**Comment by lucacozzuto** [comment]
Thanks @lpryszcz! I would need some test case (fast5 files) and the dna_r9.4.1_450bps_hac.cfg  file... I would also need the command line for porechop if we want to give this possibility... Maybe is easier if we meet for 5 minutes... what do you think?

**Comment by lucacozzuto** [comment]
Ok we are in a philosophical problem :) I would like to keep independent and separate the two processes base calling and demultiplexing... so I would like to run guppy twice one for basecalling and one for demultiplexing... is this possible? In this way I can allow any kind of combination between albacore / porechop/ guppy and the custom tool for RNA

**Comment by lucacozzuto** [comment]
Hi, please remember to send me examples and the command line for porechop

**Comment by Huanle** [comment]
@obegik can you forward the ones you used for this practice?

**Comment by obegik** [comment]
I used the default (75%) and 50% threshold.The following is the commond line for pore chop

porechop -i input_reads.fastq.gz -b output_dir --barcode_threshold 50

Oguzhan

**Comment by lucacozzuto** [comment]
> --require_barcodes_both_ends

Hi @lpryszcz I found that without "--require_barcodes_both_ends" you don't have any demultiplexing... is this normal?

**Comment by obegik** [comment]
It is normal if you are using our test data because it does not have
barcodes in both ends.

**Comment by lucacozzuto** [comment]
thanks! now I miss a dataset where I can find demultiplexed reads... do you have one?

**Comment by obegik** [comment]
You want the de multiplexed fastq files, is that correct?

**Comment by lucacozzuto** [comment]
no; I want fast5 or multifast5 that can be demultiplexed with a kit...

**Comment by obegik** [comment]
But you already used it and found that it does not demultiplex anything
with "require both barcode ends". Right?

**Comment by lucacozzuto** [comment]
without require_bot it does'nt demultiplex. With you have only unclassified

**Comment by lucacozzuto** [comment]
Hi, I'm trying porechop. How can I specify the adapter kit used? I got this:
  Error: no barcodes were found, so Porechop cannot perform barcode demultiplexing

**Comment by obegik** [comment]
Hi,

Are you testing pore chop with your fastq reads or fast5 ? In the case of fastq reads, you don’t need to specify the adapter kit.



Oguzhan

**Comment by lucacozzuto** [comment]
Hi, porechop fails if no barcode is found. Can you send me an example for testing it (a link on the cluster), please?

**Comment by obegik** [comment]
Hi Luca,

Sorry I was on holidays and did not have access to internet for sometime. I done understand the situation where the barcode is not found. I use “unclassified.fastq” file from the guppy output to perform pore chop. How do you perform it ?



Oguzhan

**Comment by lucacozzuto** [comment]
Hi,

I need examples where we found barcodes. With porechop if no barcodes are
found it simply exit with an error. Do we have data with barcodes?


Il lun 2 set 2019, 17:27 Oguzhan Begik <notifications@github.com> ha
scritto:

**Comment by obegik** [comment]
Hi Luca,

The data I gave you before, which is the run with ID cDNAB120905 should have the barcodes. After basecalling with guppy, you will have a fasta file that will have “unclassified” reads. You can use this file to run the pore chop. If you cannot produce this, I can place the unclassified.fastq file to the cluster.



Oguzhan

**Comment by lucacozzuto** [comment]
I don't want to make a two step demultiplexing (we are not yet giving this
possibility). So please send me these files.

Thanks

Il lun 2 set 2019, 17:59 Oguzhan Begik <notifications@github.com> ha
scritto:

**Comment by obegik** [comment]
HI Luca,

I placed the unclassified.fq.gz file to the public folder on cluster. The location is below:

/users/enovoa/novoalab_public/porechop_input/

Cheers,
Oguzhan

**Comment by lucacozzuto** [comment]
Hi, the pipelines need fast5 files. We don't start from fastqc... can you send me the original fast5?

**Comment by obegik** [comment]
Hi Luca,

That's actually what I was referring to before. I already shared with you
the fast5 files (the ones you use for Guppy)

**Comment by lucacozzuto** [comment]
can you share them again? Maybe I lost some passage...

**Comment by obegik** [comment]
/no_backup_isis/enovoa/data/ont/rt_cDNA/cDNAB120905_both_good

**Comment by lucacozzuto** [comment]
ok the reference is?

**Comment by lucacozzuto** [comment]
which kit is? How can I specify it in the porechop command line?

**Comment by obegik** [comment]
The reference is attached. The kit used is DCS109- EXP-NBD104

**Comment by lucacozzuto** [comment]
attached where? : )
Is curlcake_constructs?

**Comment by lucacozzuto** [comment]
wait you say in a previous post that porechop doesn't need the kit if you start from fast5 files (we use either guppy or albacore for basecalling) so I can skip the kit.

**Comment by obegik** [comment]
Sorry here it is 
[yeast_rRNA_ref.txt](https://github.com/biocorecrg/master_of_pores/files/3575235/yeast_rRNA_ref.txt)

**Comment by obegik** [comment]
In the case of fastq reads, you don’t need to specify the adapter kit.For fast5, I guess you might need to specify, I don’t know. I always use pore chop with fast

Oguzhan Begik, Ph.D. Student
Epitranscriptomics and RNA Dynamics Lab
Gene Regulation,Stem Cells and Cancer Department
Centre for Genomic Regulation
Carrer del Dr. Aiguader, 88 PRBB Building
Phone: +34-0-698-85-13-08

**Comment by lucacozzuto** [comment]
Ok many thanks! I'll close this (and open a new one if I find some issue)
