### ISSUE TITLE
--num_callers options for speeding guppy v3.4.1

### ISSUE THREAD

**Issue by lpryszcz** [biocorecrg/master_of_pores#9]
Hi @lucacozzuto , it'd be good to add and option `--num_callers` as this can speed up guppy 2x. For more have a loot at https://twitter.com/lpryszcz/status/1204854476949139463
Default one in v3.4.1 `--num_callers 1` uses little vRAM (1.2GB) but is slower ~2x slower than `--num_callers 4` that uses only 3.2GB vRAM. There is no benefit of using more than `--num_callers 4` on RTX2080 Ti.

**Comment by lucacozzuto** [comment]
it is already implemented... it is connected to cpus value in the config file... I see that for GPU is absent (so it is 1) but we can add it easily (the problem is that can be misleading since cpu, gpu... :/ )

**Comment by lucacozzuto** [comment]
Added
