### ISSUE TITLE
NanoCount: error: unrecognized arguments: NanoCount

### ISSUE THREAD

**Issue by clsgithubusr** [biocorecrg/master_of_pores#92]
Hello
Our MasterOfPores user is trying to use the NanoCount option in the counter_opt parameters.

But then she received the following error when running her pipeline:

```bash
Process `counting (fast5)` terminated with an error exit status (2)

Command executed:

NanoCount -i fast5.minimap2.sorted.bam -o fast5.count NanoCount;
awk '{sum+=$3}END{print FILENAME" "sum}' fast5.count |sed s@.count@@g > fast5.stats
samtools view -F 256 fast5.minimap2.sorted.bam |cut -f 1,3 > fast5.assigned

Command exit status:
2

Command output:
(empty)

Command error:
usage: NanoCount [-h] [--version] -i ALIGNMENT_FILE [-o COUNT_FILE]
[-l MIN_READ_LENGTH] [-f MIN_QUERY_FRACTION_ALIGNED]
[-t EQUIVALENT_THRESHOLD] [-s SCORING_VALUE]
[-c CONVERGENCE_TARGET] [-e MAX_EM_ROUNDS] [-x] [-v] [-q]
NanoCount: error: unrecognized arguments: NanoCount
```

the `NanoCount -i fast5.minimap2.sorted.bam -o fast5.count NanoCount; ` command is generated from  the nanopreprocess.nf file
it is also using the biocorecrg-mopprepr-0.6.img container to run the commands.

**Comment by eylenth** [comment]
@lucacozzuto or @ADelgadoT , do you have any suggestions on this ?
We will probably need to modify the Nanocount parameter or we need to use another version of the biocorecrg-mopprepr img container.

**Comment by ADelgadoT** [comment]
Hi, 

To use NanoCount in MoP, you don't need to write _NanoCount_ in the counter_opt parameter in the `params.config` file. MasterOfPores will run NanoCount if you are mapping to the transcriptome and the counter parameter is YES. 

Your params.config file should contain the following lines to run NanoCount:
```
ref_type = "transcriptome"
counter = "YES"
```

The parameter counter_opt is used to introduce additional parameters to NanoCount command,  for example, to only take into account primary alignments, etc. [https://adrienleger.com/NanoCount/NanoCount_CLI_usage/].

I can run NanoCount with MoP when using these options - tell me if it works for you too. 

Thanks, 

Anna

**Comment by eylenth** [comment]
Hi Anna

THe end user reported that is now working for her with those settings.

The ticket can be closed.
