### ISSUE TITLE
Could not install albacore

### ISSUE THREAD

**Issue by manburst** [biocorecrg/master_of_pores#93]
Hello sir
I try to install albacore follow by your installation instruction
which is
`git clone --depth 1 https://github.com/biocorecrg/master_of_pores.git`
and then
`cd master_of_pores/NanoPreprocess/bin`
Now here the problem
`ip3 install --target=./albacore ont_albacore-2.1.7-cp36-cp36m-manylinux1_x86_64.whl`
The error message said that 
`ERROR: Could not install packages due to an EnvironmentError: [Errno 2] No such file or directory: '/home/jirachote/master_of_pores/NanoPreprocess/bin/ont_albacore-2.1.7-cp36-cp36m-manylinux1_x86_64.whl'
`
How to fix this thanks in advance.
Ps. I check inside the bin folder of nanoprocess on GitHub, there is also no folder of tar file of guppy. Where are they?

**Comment by lucacozzuto** [comment]
Dear @manburst, because of redistribution restriction of the basecallers Albacore and Guppy we cannot provide them inside the docker image, so you would need to download the binaries from the official website https://nanoporetech.com and place them inside the master_of_pores/NanoPreprocess/bin folder. For installing Guppy you need to install the tarball file.

**Comment by manburst** [comment]
Oh, thanks for replying. I got guppy by using `sudo apt install ont-guppy`  Do I have to move them to bin folder or not?

**Comment by lucacozzuto** [comment]
You need to download the tarball version sorry. Then You can follow the documentation.

**Comment by manburst** [comment]
Sir, I have installed albacore and try to run with the mini test dataset. I have many questions right now
1. I have installed nextflow already but it is not in the nanopreprocess folder so I have moved them to the folders, do I have to move them again when I want to run nanomod and nanotail?
2. I have tried with this command
`./nextflow run nanopreprocess.nf –basecaller albacore –seqtype cDNA –fast5 "/home/jirachote/test-datasets/fast5/nonbarcoded" –demultiplexing "OFF" –map_type "spliced" –mapper_opt "-uf -k14" –reference /home/jirachote/hg19_KCMF1.fa –mapper minimap2 –ref_type “genome” –filter nanofilt –filter_opt "-q 0 –headcrop 5 –tailcrop 3 –readtype 1D"` which is copy from the publication but I edit to my path
but the error said
`Unknown option: -uf -k14 -- Check the available commands and options and syntax with 'help'`
`Unknown option: -q 0 –headcrop 5 –tailcrop 3 –readtype 1D -- Check the available commands and options and syntax with 'help'`
I don't understand how this happened so I removed `–mapper_opt “-uf -k14”` and `–filter_opt “-q 0 –headcrop 5 –tailcrop 3 –readtype 1D”` Now it can run. However,
3. Requirement problem
`Error executing process > 'testInput (multifast5_1.fast5) 'Caused by:
  Process requirement exceed available memory -- req: 12 GB; avail: 1.9 GB`
How to add parameters to set maximum memory, cpus and times for running?
Generally, I use `--max cpus --max_memory --max_time` which is hidden parameters from nextflow but can I set them in master of pores?
And I found that options that I input didn't change the pipeline
I set reference as `–ref_type “genome”` but the pipeline show as transcriptome, also the basecaller, which should be albacore not guppy.
Here is what happened in my terminal.
```
N E X T F L O W  ~  version 20.10.0
Launching `nanopreprocess.nf` [nauseous_aryabhata] - revision: 9b1fb78da4
╔╦╗┌─┐┌─┐┌┬┐┌─┐┬─┐  ┌─┐┌─┐  ╔═╗╔═╗╦═╗╔═╗╔═╗
║║║├─┤└─┐ │ ├┤ ├┬┘  │ │├┤   ╠═╝║ ║╠╦╝║╣ ╚═╗
╩ ╩┴ ┴└─┘ ┴ └─┘┴└─  └─┘└    ╩  ╚═╝╩╚═╚═╝╚═╝
                                                                                       
====================================================
BIOCORE@CRG Preprocessing of Nanopore direct RNA - N F  ~  version 0.1
====================================================

kit                       : SQK-RNA001
flowcell                  : FLO-MIN106
fast5                     : /home/jirachote/master_of_pores/NanoPreprocess/../data/multifast/*.fast5
reference                 : /home/jirachote/master_of_pores/NanoPreprocess/../anno/curlcake_constructs.fasta.gz
annotation                : 

ref_type                  : transcriptome
seq_type                  : RNA

output                    : /home/jirachote/master_of_pores/NanoPreprocess/output
qualityqc                 : 5
granularity               : 

basecaller                : guppy
basecaller_opt            : 
GPU                       : OFF
demultiplexing            :  
demultiplexing_opt        : -m pAmps-final-actrun_newdata_nanopore_UResNet20v2_model.030.h5 

filter                    : 
filter_opt                : 
mapper                    : minimap2
mapper_opt                : -uf -k14
map_type                  : unspliced

counter                   : NO
counter_opt               : 

email                     :
[-        ] process > testInput             [  0%] 0 of 1
[-        ] process > baseCalling           -
[-        ] process > concatenateFastQFiles -
[-        ] process > QC                    -
[07/c8e7df] process > testInput (multifast5_1.fast5) [100%] 1 of 1, failed: 1
[-        ] process > baseCalling                    -
[-        ] process > concatenateFastQFiles          -
[-        ] process > QC                             -
[-        ] process > fastQC                         -
[-        ] process > mapping                        -
[-        ] process > alnQC                          -
[-        ] process > joinAlnQCs                     -
[-        ] process > alnQC2                         -
[-        ] process > multiQC                        -
Error executing process > 'testInput (multifast5_1.fast5)'

Caused by:
  Process requirement exceed available memory -- req: 12 GB; avail: 1.9 GB

Command executed:

  fast5_type.py multifast5_1.fast5

Command exit status:
  -

Command output:
  (empty)

Work dir:
  /home/jirachote/master_of_pores/NanoPreprocess/work/07/c8e7df602943391cc6e7dec968a51c

Tip: view the complete command output by changing to the process work dir and entering the command `cat .command.out`

```
Thanks in advance.

**Comment by lucacozzuto** [comment]
Hi,
1. nextflow can be outside. I would add it to the $PATH
2. you need to specify the parameters using two "-"  (--) so:  –-basecaller and not  –basecaller. One "-" allows specifying nextflow parameters.
3. you can change the resources changing the file nextflow.global.config

**Comment by manburst** [comment]
Sir, another question, please.
I have troubled to target fast5 file in my directory it only detects a single fast5 in my directory
`--fast5 /home/jirachote/test-datasets/fast5/nonbarcoded/*`
Here it will show
single fast5 detect
`fast5                     : /home/jirachote/test-datasets/fast5/nonbarcoded/GISPC970_20180731_FAJ05143_MN20082_sequencing_run_310718_MCF7_mRNA_directcDNA_37492_read_7_ch_100_strand.fast5`
and when it finished even the result showed basecalling is success but I have check the output it is empty fastq file.
I have tried with 
`--fast5 /home/jirachote/test-datasets/fast5/nonbarcoded/*.fast5`
but it give me an error
So, how to input multiple fast5 in one time?
Thanks in advance

**Comment by lucacozzuto** [comment]
--fast5 "/home/jirachote/test-datasets/fast5/nonbarcoded/*.fast5" should work

**Comment by manburst** [comment]
Thank you, sir! Now, it worked perfectly.
I am continuing with nanotail process with results from the DNA dataset of nanopreprocess. Do I have to install the nanopolish and tailfindr?
Because I already run them and it gives me an error as expected
```
./nextflow run nanotail.nf -with-docker --input_folders "NanoPreprocess/output" --nanopolish_opt "" --tailfindr_opt "" --reference "/home/jirachote/hg19_KCMF1.fa"
N E X T F L O W  ~  version 20.10.0
Launching `nanotail.nf` [magical_yonath] - revision: 9c54218c64
╔╦╗┌─┐┌─┐┌┬┐┌─┐┬─┐  ┌─┐┌─┐  ╔═╗╔═╗╦═╗╔═╗╔═╗
║║║├─┤└─┐ │ ├┤ ├┬┘  │ │├┤   ╠═╝║ ║╠╦╝║╣ ╚═╗
╩ ╩┴ ┴└─┘ ┴ └─┘┴└─  └─┘└    ╩  ╚═╝╩╚═╚═╝╚═╝
                                                                                       
====================================================
BIOCORE@CRG NanoTail. Detection of polyA length (RNA) - N F  ~  version 0.1
====================================================

*****************   Input files    *********************
input_folders            : NanoPreprocess/output

******* reference has to be the genome **********
reference                : /home/jirachote/hg19_KCMF1.fa
output                   : /home/jirachote/master_of_pores/NanoTail/outputRNA

********* nanopolish and tailfindr cmd options **********
nanopolish_opt           : true 
tailfindr_opt            : true 

email                     : yourname@yourdomain
executor >  local (2)
[45/48f10e] process > check_reference            [100%] 1 of 1 ✔
[-        ] process > tailfindr                  -
[97/e485df] process > filter_bam (output)        [  0%] 0 of 1 ✔
[-        ] process > tail_nanopolish            -
executor >  local (2)
[45/48f10e] process > check_reference            [100%] 1 of 1 ✔
[-        ] process > tailfindr                  -
[97/e485df] process > filter_bam (output)        [100%] 1 of 1 ✔
[-        ] process > tail_nanopolish            -
[-        ] process > collect_nanopolish_results -
[-        ] process > collect_tailfindr_results  -
[-        ] process > join_results               -
Failed to invoke `workflow.onComplete` event handler

 -- Check script 'nanotail.nf' at line: 303 or see '.nextflow.log' file for more details
Completed at: 05-Feb-2021 07:44:16
Duration    : 5m 34s
CPU hours   : 0.2
Succeeded   : 2

```
The line 303 of nanotail.nf is
`sendMail(to: params.email, subject: "Master of Pore execution", body: msg)`

**Comment by lucacozzuto** [comment]
No you don't need to install anything. Docker is enough. The error is just related to the mail system that is failing. So it is not the problem here. Have you read the documentation here https://biocorecrg.github.io/master_of_pores/nanotail.html ? You need to run nanopreprocess setting --counting "YES" since you need to assign each read to a gene. You can rerun nanopreprocess adding this parameter and using -resume so you will skip all the steps already done

**Comment by manburst** [comment]
Edit I have run resume the test 
`./nextflow run nanopreprocess.nf -with-docker --basecaller guppy --seq_type "DNA" --fast5 "/home/jirachote/test-datasets/fast5/nonbarcoded/*.fast5" --demultiplexing "OFF" --map_type "spliced" --mapper_opt "-uf -k14" --reference /home/jirachote/hg19_KCMF1.fa --mapper minimap2 --ref_type "genome" --filter nanofilt --filter_opt "-q 0 -headcrop 5 -tailcrop 3 -readtype 1D" --flowcell FLO-MIN106 --kit SQK-LSK109 --counter "YES" --counter_opt "genome"  -resume`
and got this error
```
====================================================
BIOCORE@CRG Preprocessing of Nanopore direct RNA - N F  ~  version 0.1
====================================================

kit                       : SQK-LSK109
flowcell                  : FLO-MIN106
fast5                     : /home/jirachote/test-datasets/fast5/nonbarcoded/*.fast5
reference                 : /home/jirachote/hg19_KCMF1.fa
annotation                : 

ref_type                  : genome
seq_type                  : DNA

output                    : /home/jirachote/master_of_pores/NanoPreprocess/output
qualityqc                 : 5
granularity               : 

basecaller                : guppy
basecaller_opt            : 
GPU                       : OFF
demultiplexing            : OFF 
demultiplexing_opt        : -m pAmps-final-actrun_newdata_nanopore_UResNet20v2_model.030.h5 

filter                    : nanofilt
filter_opt                : -q 0 -headcrop 5 -tailcrop 3 -readtype 1D
mapper                    : minimap2
mapper_opt                : -uf -k14
map_type                  : spliced

counter                   : YES
counter_opt               : genome

email                     :
[18/e93628] process > testInput (GISPC970_20180731_FAJ05143_MN20082_sequencing_run_31... [100%] 1 of 1, cached: 1 ✔
[d5/1f1303] process > baseCalling (guppy-nonbarcoded-0)                                  [100%] 1 of 1, cached: 1 ✔
[4a/1066cd] process > filtering (nanofilt-0)                                             [100%] 1 of 1, cached: 1 ✔
[5e/bf69ac] process > concatenateFastQFiles (nonbarcoded)                                [100%] 1 of 1, cached: 1 ✔
[f0/614c39] process > QC (nonbarcoded)                                                   [100%] 1 of 1, cached: 1 ✔
[45/abaf90] process > fastQC (nonbarcoded)                                               [100%] 1 of 1, cached: 1 ✔
[5b/f90ac3] process > mapping (minimap2-nonbarcoded)                                     [100%] 1 of 1, cached: 1 ✔
[-        ] process > counting                                                           -
[-        ] process > joinCountQCs                                                       -
[3d/d580cf] process > alnQC (nonbarcoded)                                                [100%] 1 of 1, cached: 1 ✔
[df/0ae554] process > joinAlnQCs                                                         [100%] 1 of 1, cached: 1 ✔
[-        ] process > alnQC2                                                             -
[-        ] process > multiQC                                                            -
[18/e93628] process > testInput (GISPC970_20180731_FAJ05143_MN20082_sequencing_run_31... [100%] 1 of 1, cached: 1 ✔
[d5/1f1303] process > baseCalling (guppy-nonbarcoded-0)                                  [100%] 1 of 1, cached: 1 ✔
[4a/1066cd] process > filtering (nanofilt-0)                                             [100%] 1 of 1, cached: 1 ✔
[5e/bf69ac] process > concatenateFastQFiles (nonbarcoded)                                [100%] 1 of 1, cached: 1 ✔
[f0/614c39] process > QC (nonbarcoded)                                                   [100%] 1 of 1, cached: 1 ✔
[45/abaf90] process > fastQC (nonbarcoded)                                               [100%] 1 of 1, cached: 1 ✔
[5b/f90ac3] process > mapping (minimap2-nonbarcoded)                                     [100%] 1 of 1, cached: 1 ✔
[-        ] process > counting                                                           -
[-        ] process > joinCountQCs                                                       -
[3d/d580cf] process > alnQC (nonbarcoded)                                                [100%] 1 of 1, cached: 1 ✔
[df/0ae554] process > joinAlnQCs                                                         [100%] 1 of 1, cached: 1 ✔
[-        ] process > alnQC2                                                             [  0%] 0 of 1
[3e/356214] process > multiQC                                                            [100%] 1 of 1, cached: 1 ✔
Skipping the email
Single Fast5 files detected!
Error executing process > 'counting (nonbarcoded)'

Caused by:
  begin -3, end 0, length 0

Source block:
  if (params.ref_type == "transcriptome") {
  		}       """
  			NanoCount -i ${bamfile} -o ${idfile}.count ${counter_opt};
  p: wheawk '{sum+=\$3}END{print FILENAME"\t"sum}' ${idfile}.count |sed s@.count@@g > ${idfile}.stats
  e     samtools view -F 256 ${bamfile} |cut -f 1,3 > ${idfile}.assigned
  peline BIOCORE@CRG Mas"""
  arted at  2021} else if (params.ref_type == "genome") {
  nished at 2021-02-05T1def anno = unzipBash("${params.annotation}") 
  me elapsed: 4.2s      """
  ecution status: failedsamtools view ${bamfile} |htseq-count -f sam - ${anno} -o ${idfile}.sam > ${idfile}.count
  e/356214] Cached proceawk '{gsub(/XF:Z:/,"",\$NF); print \$1"\t"\$NF}' ${idfile}.sam |grep -v '__' > ${idfile}.assigned
  			rm ${idfile}.sam
  			"""		
  		}


```
I have checked my alignment output. Here, I got a new sorted bam file but the name is "nonbarcoded" instead of "multi"
![image](https://user-images.githubusercontent.com/68594551/107107361-1f3bdd00-6863-11eb-89c3-2610f9db49b3.png)

Edit 2 Now found the main problem it might be the input path error again even I used  `--fast5 "/home/jirachote/test-datasets/fast5/nonbarcoded/*.fast5"` They can detect only single file not multi fast5 file like before. (I used the same command to run it again which is `./nextflow run nanopreprocess.nf -with-docker --basecaller guppy --seq_type DNA --fast5 '/home/jirachote/test-datasets/fast5/nonbarcoded/*.fast5' --demultiplexing OFF --map_type spliced --mapper_opt '-uf -k14' --reference /home/jirachote/hg19_KCMF1.fa --mapper minimap2 --ref_type genome --filter nanofilt --filter_opt '-q 0 -headcrop 5 -tailcrop 3 -readtype 1D' --flowcell FLO-MIN106 --kit SQK-LSK109`  )
Here is log
Note that in fast5 is /home/jirachote/test-datasets/fast5/nonbarcoded/*.fast5 now but only detect single fast5 not mulitfast5
```
kit                       : SQK-LSK109
flowcell                  : FLO-MIN106
fast5                     : /home/jirachote/test-datasets/fast5/nonbarcoded/*.fast5
reference                 : /home/jirachote/hg19_KCMF1.fa
annotation                : 

ref_type                  : genome
seq_type                  : DNA

output                    : /home/jirachote/master_of_pores/NanoPreprocess/output
qualityqc                 : 5
granularity               : 

basecaller                : guppy
basecaller_opt            : 
GPU                       : OFF
demultiplexing            : OFF 
demultiplexing_opt        : -m pAmps-final-actrun_newdata_nanopore_UResNet20v2_model.030.h5 

filter                    : nanofilt
filter_opt                : -q 0 -headcrop 5 -tailcrop 3 -readtype 1D
mapper                    : minimap2
mapper_opt                : -uf -k14
map_type                  : spliced

counter                   : NO
counter_opt               : 

email                     :
executor >  local (11)
[a9/7fba49] process > testInput (GISPC970_20180731_FAJ05143_MN20082_sequencing_run_310718_MCF7_mRNA_directcDNA_37492_read_7_ch_345_strand.fast5) [100%] 1 of 1 ✔
[b9/4f4892] process > baseCalling (guppy-nonbarcoded-0)                                                                                          [100%] 1 of 1 ✔
[9f/a599f5] process > filtering (nanofilt-0)                                                                                                     [100%] 1 of 1 ✔
[77/6aa3e6] process > concatenateFastQFiles (nonbarcoded)                                                                                        [100%] 1 of 1 ✔
executor >  local (11)
[a9/7fba49] process > testInput (GISPC970_20180731_FAJ05143_MN20082_sequencing_run_310718_MCF7_mRNA_directcDNA_37492_read_7_ch_345_strand.fast5) [100%] 1 of 1 ✔
[b9/4f4892] process > baseCalling (guppy-nonbarcoded-0)                                                                                          [100%] 1 of 1 ✔
[9f/a599f5] process > filtering (nanofilt-0)                                                                                                     [100%] 1 of 1 ✔
[77/6aa3e6] process > concatenateFastQFiles (nonbarcoded)                                                                                        [100%] 1 of 1 ✔
[aa/d0a557] process > QC (nonbarcoded)                                                                                                           [100%] 1 of 1 ✔
[82/c43f5b] process > fastQC (nonbarcoded)                                                                                                       [100%] 1 of 1 ✔
[c4/9a4cac] process > mapping (minimap2-nonbarcoded)                                                                                             [100%] 1 of 1 ✔
[16/d21297] process > alnQC (nonbarcoded)                                                                                                        [100%] 1 of 1 ✔
[3d/c41818] process > joinAlnQCs                                                                                                                 [100%] 1 of 1 ✔
[15/817d94] process > alnQC2 (nonbarcoded)                                                                                                       [100%] 1 of 1, failed: 1 ✔
[e4/5f4064] process > multiQC                                                                                                                    [100%] 1 of 1 ✔
[15/817d94] NOTE: Process `alnQC2 (nonbarcoded)` terminated with an error exit status (1) -- Error is ignored
Completed at: 05-Feb-2021 20:51:35
Duration    : 4m 33s
CPU hours   : 0.1 (4.7% failed)
Succeeded   : 10
Ignored     : 1
Failed      : 1

```
I have reinstalled the master of pore but it still gives me the same result. Only one time that pipeline can detect multiple fast5 file in my folder.

**Comment by manburst** [comment]
Sir, could you please check my command line again
I think this command that complete job successful at that time, it can detect all fast5 file in my directory
`./nextflow run nanopreprocess.nf -with-docker --basecaller guppy --seq_type DNA --fast5 "/home/jirachote/nonbarcoded/*.fast5" --demultiplexing "OFF" --map_type spliced --mapper_opt "-uf -k14" --reference "/home/jirachote/hg19_KCMF1.fa" --mapper minimap2 --ref_type genome --filter nanofilt --filter_opt '-q 0 -headcrop 5 -tailcrop 3 -readtype 1D' --flowcell FLO-MIN106 --kit SQK-LSK109`
but I don't understand why I repeat the same command but the problem to detect all fast5 files come back again. I don't know what I missed in the command line and why the pipeline detects only a single fast5 file in my directory again.

**Comment by lucacozzuto** [comment]
Hi, I see a wrong option before no? << --counter_opt "genome" >>

**Comment by manburst** [comment]
Oh, I see. Just leave `counter_opt ""` right?
but I still don't get why `fast5` parameter detects only one fast5 file in my directory. 
`"/home/jirachote/nonbarcoded/*.fast5"`
`Single fast5 file detect`

**Comment by lucacozzuto** [comment]
single fast5 means that is containing only one sequence per file. Is this true?

**Comment by manburst** [comment]
Yes, one read per file. In comment above that you suggests me to you use parameter `--fast5 "/home/jirachote/nonbarcoded/*.fast5"`. The pipeline run successfully with perfect result. But I repeat the step, the result fail because I check the fastq directory. The fastq file is empty.

**Comment by lucacozzuto** [comment]
So you cannot mix single and multifast5 files. Are you mixing single and multi?

**Comment by manburst** [comment]
I don't know am I understand your question right. But the problem is the input should be all fast5 file in my directory which is single read per file then they should be performed by basecaller then merge to multifast5 file.

**Comment by lucacozzuto** [comment]
MoP can analyze in a single run only one kind of data: either fast5 files containing one sequence each or multi fast5 files containing 5000 sequences each.

**Comment by manburst** [comment]
Got it thanks sir.

**Comment by lucacozzuto** [comment]
you are welcome!
