### ISSUE TITLE
unexpected BAM file is only 1KB with a successful run

### ISSUE THREAD

**Issue by AhmedMohamed1993** [biocorecrg/master_of_pores#94]
Hi, 

This is my first time to work with ONT data. I used the nanopreprocess pipeline to analyze the fat5 files. However, the bam file shows up as 1KB only after completing the nanopreprocess with only one error as shown on the log below.
Also, the fast5.assigned is ZERO KB and the count file has no information 1KB and the fastq file is only one file around 1.5GB while the fast5 input was 170GB, Is that normal ?

$ nextflow run /master_of_pores/NanoPreprocess/nanopreprocess.nf --kit "SQK-RNA002" --flowcell "FLO-MIN106" --fast5 "/fast5/F*.fast5" --output "/MasterOfPores_results/090321" --counter "YES" -with-singularity

**RUN_LOG:**

kit                       : SQK-RNA002
flowcell                  : FLO-MIN106
fast5                     : /fast5/F*.fast5
reference                 : /master_of_pores/NanoPreprocess/../anno/curlcake_constructs.fasta.gz
annotation                : 

ref_type                  : transcriptome
seq_type                  : RNA

output                    : /MasterOfPores_results/090321
qualityqc                 : 5
granularity               : 

basecaller                : guppy
basecaller_opt            : 
GPU                       : OFF
demultiplexing            :  
demultiplexing_opt        : -m pAmps-final-actrun_newdata_nanopore_UResNet20v2_model.030.h5 

filter                    : 
filter_opt                : 
mapper                    : minimap2
mapper_opt                : -uf -k14
map_type                  : unspliced

counter                   : YES
counter_opt               : 

email                     : 

[85/d98b2d] process > testInput (FAL20046_skip_3b... [100%] 1 of 1 ✔
[9e/30d1a0] process > baseCalling (guppy-fast5-461)  [100%] 462 of 462 ✔
[10/3f8c65] process > concatenateFastQFiles (fast5)  [100%] 1 of 1 ✔
[96/d7210c] process > QC (fast5)                     [  0%] 0 of 1
[9a/1572dc] process > fastQC (fast5)                 [  0%] 0 of 1
[9a/ddc411] process > mapping (minimap2-fast5)       [100%] 1 of 1 ✔
[c6/551cf9] process > counting (fast5)               [100%] 1 of 1 ✔
[f4/73c1fc] process > joinCountQCs                   [100%] 1 of 1 ✔
[2c/161acb] process > alnQC (fast5)                  [100%] 1 of 1 ✔
[d0/a788b6] process > joinAlnQCs                     [100%] 1 of 1 ✔
[d4/27e16d] process > alnQC2 (fast5)                 [100%] 1 of 1, failed: 1 ✔
[-        ] process > multiQC                        -
[d4/27e16d] NOTE: Process `alnQC2 (fast5)` terminated with an error exit status (1) -- Error is ignored

[85/d98b2d] process > testInput (FAL20046_skip_3b... [100%] 1 of 1 ✔
[9e/30d1a0] process > baseCalling (guppy-fast5-461)  [100%] 462 of 462 ✔
[10/3f8c65] process > concatenateFastQFiles (fast5)  [100%] 1 of 1 ✔
[96/d7210c] process > QC (fast5)                     [100%] 1 of 1 ✔
[9a/1572dc] process > fastQC (fast5)                 [100%] 1 of 1 ✔
[9a/ddc411] process > mapping (minimap2-fast5)       [100%] 1 of 1 ✔
[c6/551cf9] process > counting (fast5)               [100%] 1 of 1 ✔
[f4/73c1fc] process > joinCountQCs                   [100%] 1 of 1 ✔
[2c/161acb] process > alnQC (fast5)                  [100%] 1 of 1 ✔
[d0/a788b6] process > joinAlnQCs                     [100%] 1 of 1 ✔
[d4/27e16d] process > alnQC2 (fast5)                 [100%] 1 of 1, failed: 1 ✔
[d3/f6b166] process > multiQC                        [100%] 1 of 1 ✔

**Any suggestions about cause or error or modifications required ?**
Thanks in advance! :)

**Comment by lucacozzuto** [comment]
Hi!
you are using our toy reference 

```
 reference : /master_of_pores/NanoPreprocess/../anno/curlcake_constructs.fasta.gz
```
you need to point to the genome / transcriptome for your species of interest.

Best,

Luca

**Comment by AhmedMohamed1993** [comment]
Hi,

Oh, I am working on mouse data so, I should add the parameter --ref_type "mm10" ? Is the reference genome built-in with the tool or I have to download the GTF file from Ensemble and refer to its location in the parameter argument ?
Thanks again and sorry for the stupid question.

**Comment by lucacozzuto** [comment]
You have to provide a fasta file for a genome and a GTF annotation, or in case you want to use the transcriptome just the fasta of the transcriptome sequences.  You can choose either Gencode, Ensembl or UCSC.
