### ISSUE TITLE
Error during NanoPreprocess step

### ISSUE THREAD

**Issue by chad388** [biocorecrg/master_of_pores#96]
Hi,

I am encountering an error when I attempt to run the NanoPreprocess step. 

We are required to install any software that we run on our system within a docker container. We are unable to install any software directly on the filesystem. 

I followed the installation process described here (https://biocorecrg.github.io/master_of_pores/install.html) and installed all required software into a docker container named ctomlins/nanoporerna:latest which I pushed up to dockerhub. I installed the latest version of Guppy and did not install Albacore.

I then pulled down the ctomlins/nanoporerna:latest within an interactive bash shelll on my system and attempted to run the nanopreprocessing step, but I am getting the error below. 

Command error:
  .command.sh: line 2: /master_of_pores/NanoPreprocess/bin/fast5_type.py: No such file or directory

**Below is the full output of my job**

nextflow run nanopreprocess.nf
/usr/bin/nextflow: line 462: printf: write error: Disk quota exceeded
N E X T F L O W  ~  version 20.10.0
Launching `nanopreprocess.nf` [awesome_raman] - revision: 6b404cb205
╔╦╗┌─┐┌─┐┌┬┐┌─┐┬─┐  ┌─┐┌─┐  ╔═╗╔═╗╦═╗╔═╗╔═╗
║║║├─┤└─┐ │ ├┤ ├┬┘  │ │├┤   ╠═╝║ ║╠╦╝║╣ ╚═╗
╩ ╩┴ ┴└─┘ ┴ └─┘┴└─  └─┘└    ╩  ╚═╝╩╚═╚═╝╚═╝
                                                                                       
====================================================
BIOCORE@CRG Preprocessing of Nanopore direct RNA - N F  ~  version 0.1
====================================================
kit                       : SQK-RNA002
flowcell                  : FAN02745
fast5                     : /gscmnt/sata130/graveslab/Oxford_Nanopore_Instrument_Data/Direct_RNA_Seq/Pan_Genome_sample/20210224_1836_X1_FAN02745_b6677fd0/fast5_pass/*.fast5
reference                 : /gscmnt/sata130/graveslab/Oxford_Nanopore_Instrument_Data/Direct_RNA_Seq/Direct_RNA_Seq_Analysis/Reference/Transcriptome/Homo_sapiens.GRCh38.cdna.all.fa.gz
annotation                : 
ref_type                  : transcriptome
seq_type                  : RNA
output                    : /gscmnt/sata130/graveslab/Oxford_Nanopore_Instrument_Data/Direct_RNA_Seq/Direct_RNA_Seq_Analysis/ctomlins_test/NanoPreprocess_Output
qualityqc                 : 5
granularity               : 
basecaller                : guppy
basecaller_opt            : 
GPU                       : OFF
demultiplexing            :  
demultiplexing_opt        :  
filter                    : OFF
filter_opt                : 
mapper                    : minimap2
mapper_opt                : -uf -k14
map_type                  : unspliced
counter                   : YES
counter_opt               : NanoCount
email                     : ctomlins@wustl.edu
executor >  lsf (1)
[b7/8919d9] process > testInput (FAN02745_pass_6de2868e_182.fast5) [100%] 1 of 1, failed: 1 ✘
[-        ] process > baseCalling                                  -
[-        ] process > concatenateFastQFiles                        -
[-        ] process > QC                                           -
[-        ] process > fastQC                                       -
[-        ] process > mapping                                      -
[-        ] process > counting                                     -
[-        ] process > joinCountQCs                                 -
[-        ] process > alnQC                                        -
[-        ] process > joinAlnQCs                                   -
[-        ] process > alnQC2                                       -
[-        ] process > multiQC                                      -
Error executing process > 'testInput (FAN02745_pass_6de2868e_182.fast5)'

Caused by:
  Process `testInput (FAN02745_pass_6de2868e_182.fast5)` terminated with an error exit status (1)

Command executed:

  /master_of_pores/NanoPreprocess/bin/fast5_type.py FAN02745_pass_6de2868e_182.fast5

Command exit status:
  1

Command output:
  (empty)

Command error:
  .command.sh: line 2: /master_of_pores/NanoPreprocess/bin/fast5_type.py: No such file or directory

Work dir:
  /gscmnt/sata130/graveslab/Oxford_Nanopore_Instrument_Data/Direct_RNA_Seq/Direct_RNA_Seq_Analysis/ctomlins_test/work/b7/8919d9d370c7ead6bc615553215b96

Tip: you can replicate the issue by changing to the process work dir and entering the command `bash .command.run`
Failed to invoke `workflow.onComplete` event handler

 -- Check script 'nanopreprocess.nf' at line: 665 or see '.nextflow.log' file for more details
Pipeline BIOCORE@CRG Master of Pore completed!
Started at  2021-04-23T18:30:51.780499-05:00
Finished at 2021-04-23T18:34:14.004699-05:00
Time elapsed: 3m 22s
Execution status: failed

When I am sitting in my docker container ctomlins/nanoporerna:latest the fast5_type.py file is located at the path below, but for some reason the pipeline is not finding it:

/master_of_pores/NanoPreprocess/bin/fast5_type.py

Do you happen to have a dockerfile containing the the various files such as fast5_type.py that are pulled from the MasterOfPores github repo?

Below is a copy of how I have the nextflow.global.config setup. I am attempting to load my docker container during the first process step. Is there a different way that I should be doing this?

more nextflow.global.config 
singularity.autoMounts = true

env {
  PYTHONNOUSERSITE = 1
}

process {
  memory='12G'
  cache='lenient'
  container = 'docker(ctomlins/nanoporerna)'
  containerOptions = { workflow.containerEngine == "docker" ? '-u $(id -u):$(id -g)': null}
  withLabel: big_cpus {
        cpus = 8
        memory = '12M'
	clusterOptions = "-a 'docker(ctomlins/nanoporerna)' -q ccdg"
  }
  withLabel: big_mem_cpus {
        cpus = 8
        memory = '20M'
	clusterOptions = "-a 'docker(biocorecrg/mopprepr:0.6)' -q ccdg"
  }
  withLabel: demulti {
        container = 'biocorecrg/mopdem:0.1'
        cpus = 8
        memory = '20M'
	clusterOptions = "-a 'docker(biocorecrg/mopdem:0.1)' -q ccdg"
  }
  withLabel: basecall_cpus {
        container = 'biocorecrg/mopbasecall:0.1'
        cpus = 8
        memory = '5M'
	clusterOptions = "-a 'docker(biocorecrg/mopbasecall:0.1)' -q ccdg"
  }
  withLabel: basecall_gpus {
        container = 'biocorecrg/mopbasecall:0.1'
        cpus = 2 
        maxForks = 1
        containerOptions = { workflow.containerEngine == "singularity" ? '--nv':
           ( workflow.containerEngine == "docker" ? '-u $(id -u):$(id -g) --gpus all': null ) } 
	clusterOptions = "-a 'docker(biocorecrg/mopbasecall:0.1)' -q ccdg"
  } 
}

profiles {
    lsf {
        process {
    		executor = 'local'
    		cpus = 2
    		memory = '12MB'    
	        clusterOptions = "-a 'docker(ctomlins/nanoporerna)' -q ccdg"
    	}
    }
}

Best,

Chad

**Comment by lucacozzuto** [comment]
Dear Chad, you don't need to install any tool in any docker container. We already have docker containers with everything installed. So, you should just install singularity or docker and nextflow.
