### ISSUE TITLE
Counts feature error during Nanopreprocess run

### ISSUE THREAD

**Issue by Maheen94** [biocorecrg/master_of_pores#97]
Hi,
I'm using master of pores for RNA seq data analysis. I used reference and annotation files from Gencode. However, I get the following error consistently at the counts step. Would really appreciate any assistance.
Thanks!!

Maheen 

<img width="1192" alt="Screen Shot 2021-05-31 at 4 30 52 PM" src="https://user-images.githubusercontent.com/83305852/120240307-41040a00-c22e-11eb-894e-047678377b32.png">

**Comment by lucacozzuto** [comment]
Hi,
it seems the file is not accessible. Can you reach the working folder indicated and check wether the link to the annotation file is working? 

Luca

**Comment by Maheen94** [comment]
Hi,

So, I uploaded the ref genome (fasta) and cooresponding annotation file (GTF) from Gencode using following commands in anno folder:

wget http://ftp.ebi.ac.uk/pub/databases/gencode/Gencode_human/release_38/GRCh38.p13.genome.fa.gz
wget http://ftp.ebi.ac.uk/pub/databases/gencode/Gencode_human/release_38/gencode.v38.chr_patch_hapl_scaff.annotation.gtf.gz

The alignment works fine but its specifically the counts function which throws an error. I also tried using other annotation files from Gencode but the same problem persisted. 

Maheen

**Comment by lucacozzuto** [comment]
Mmm... Can you try unzipping the GTF file before?
I'll double-check if this is a bug.
Thanks for letting me know!

**Comment by Maheen94** [comment]
Sure, will try unzipping the file first. Will keep you updated.

**Comment by Maheen94** [comment]
Tried rerunning it with unzipped file but ran into the same error:

Also, it says "Error occurred when processing GFF file". I always use GTF format and didn't run into issues. I'm wondering if I should use GFF3 format instead?

Command exit status:
  1

**Command output:
  (empty)

Command error:
  WARNING: Your kernel does not support swap limit capabilities or the cgroup is not mounted. Memory limited without swap.
  Error occured when processing GFF file (line 1 of file /home/ubuntu/environment/master_of_pores/NanoPreprocess/../anno/gencode.v38.chr_patch_hapl_scaff.annotation.gtf):
    [Errno 2] No such file or directory: '/home/ubuntu/environment/master_of_pores/NanoPreprocess/../anno/gencode.v38.chr_patch_hapl_scaff.annotation.gtf'
    [Exception type: FileNotFoundError, raised in __init__.py:47]**_

**Comment by lucacozzuto** [comment]
Well no. That process is using htseq-count that is able to read gtf files. So I don't understand why you have this error. But again I see a "file not found". So can you go to that temporary folder and try to see if the link is ok?

**Comment by Maheen94** [comment]
The link is actually ok. Just double checked it

**Comment by lucacozzuto** [comment]
Ok. So you can run that command just by doing 
```
singularity exec -e NAMEOFIMAGE .command.sh 
```

the name of the image can be retrieved by doing a 

```grep singu .command.run```

**Comment by Maheen94** [comment]
Command 'singularity' not found, but can be installed with:

I'm using docker,
I normally start my pipeline with the following command:
nextflow run nanopreprocess.nf -with-docker

**Comment by lucacozzuto** [comment]
Aha. Well, maybe there is a problem with the mounting of volumes and docker. So grep docker inside the .command.run you will find the command to use.

**Comment by Maheen94** [comment]
Hi,
So, I changed some parameters of params.config.
Previous: ref_type "genome" (theoretically this makes sense since I'm using genome ref)
Changed: ref_type "transcriptome" (It ran smoothly on this setting even though I used the same ref genome uploaded in the anno folder using the wget command)

**Comment by lucacozzuto** [comment]
Changing to transcriptome will change the tool for counting. So something weird is happening with htseq-count tool. Did you solve it?

**Comment by ash-kh** [comment]
I have the same error too, tried it with both gz and gunziped format. The command works well when I run it using the systems htseq but fails when using the singularity container. 

The transcriptome mapping works

**Comment by lucacozzuto** [comment]
Ouch. Can you send me a single fast5 file for trying?

**Comment by lucacozzuto** [comment]
my email il luca.cozzuto /at/ crg . eu

**Comment by ash-kh** [comment]
Thanks for the super quick response! 

I tried it with the test data provided as well and get the same error. 

Best,
Ashkan

**Comment by lucacozzuto** [comment]
Hi, the test dataset is transcriptome. So, it won't use htseq-count (that needs the GTF annotation). If you have a single fast5 file and tell me which genome and annotation is, I'll give it a try and debug

**Comment by Maheen94** [comment]
Hi
For me the same error persisted. Only the transcriptiome mapping works.

Get Outlook for iOS<https://aka.ms/o0ukef>
________________________________

**Comment by ash-kh** [comment]
I sent you a mail

**Comment by lucacozzuto** [comment]
Hi, I replied to the mail. I was unable to reproduce the error. 
I have singularity version 3.2.1


and using this param


params {
    kit                 = "SQK-RNA001"
    flowcell            = "FLO-MIN106"
    fast5               = "$baseDir/../data/input/*.fast5"
    reference           = "$baseDir/../anno/GRCh38.primary_assembly.genome.fa.gz"
    annotation          = "$baseDir/../anno/gencode.v38.annotation.gtf"
    ref_type            = "genome"

    seq_type            = "RNA"
    output              = "$baseDir/output"
    qualityqc           = 5
    granularity         = ""

    basecaller          = "guppy"
    basecaller_opt      = ""
    GPU                 = "OFF"
    demultiplexing      = ""
    demultiplexing_opt  = ""
    demulti_fast5       = "OFF"

    filter              = ""
    filter_opt          = ""

    mapper              = "minimap2"
    mapper_opt          = ""
    map_type            = "spliced"

    counter             = "YES"
    counter_opt         = ""

    variant_caller      = "NO"
    variant_opt         = ""

    downsampling        = ""

    email               = "" 
    }

**Comment by lucacozzuto** [comment]
Hi, it looks like htseq has a problem with some long-read mappers. We fix this in the version of master of pores:

https://github.com/biocorecrg/MOP2
